// SPDX-License-Identifier: Apache-2.0
#pragma once

#include "runtime_add_float.h"
#include "runtime_add_int8.h"
#include "runtime_averagepool_float.h"
#include "runtime_batchnormalization_float.h"
#include "runtime_batchnormalization_int8.h"
#include "runtime_concat_float.h"
#include "runtime_conv_float.h"
#include "runtime_conv_int8.h"
#include "runtime_gemm_float.h"
#include "runtime_globalaveragepool_float.h"
#include "runtime_lrn_float.h"
#include "runtime_maxpool_float.h"
#include "runtime_maxpool_int8.h"
#include "runtime_mul_float.h"
#include "runtime_mul_int8.h"
#include "runtime_relu_float.h"
#include "runtime_relu_int8.h"
#include "runtime_reshape_float.h"
#include "runtime_softmax_float.h"
#include "runtime_sum_float.h"
#include "runtime_transpose_float.h"
#include "runtime_unsqueeze_float.h"
