(module
  (type $0 (func (result f32 (ref null extern))))
  (export "main" (func 0))
  (func $0 (type 0)
    (block (type 0)
      (f32.const 1.8)
      (i32.const 0)
      (ref.i31)
      (extern.convert_any)
      (br_on_cast 0 (ref extern) (ref extern))
      (drop)
      (drop)
      (f32.const 3.2)
      (ref.null extern)
    )
  )
)