# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      # Prefix for PR title and commit messages
      prefix: "ci(dependabot):"
    groups:
      # Group updates, actions that match are grouped into a single PR;
      # dependabot should still raise a PR for each of the remaining actions
      upload-and-download-artifact:
        patterns:
          - "*load-artifact"
      docker:
        patterns:
          - "docker/*"
