path_classifiers:
  test:
    - "test/**/*.cpp"
extraction:
  cpp:
    prepare:
      packages:
        - libboost-all-dev
        - libc++abi-9-dev
        - liblld-9-dev
        - libtbb-dev
        - llvm-9-dev
    configure:
      command:
        - cmake -GNinja -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug
    index:
      build_command:
        - ninja -C build

