// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2019-2025 Second State INC

//===-- wasmedge/wasmedge_vm.h - WasmEdge C API ---------------------------===//
//
// Part of the WasmEdge Project.
//
//===----------------------------------------------------------------------===//
///
/// \file
/// This file contains functions for WASM VM in the WasmEdge C API.
///
//===----------------------------------------------------------------------===//

#ifndef WASMEDGE_C_API_VM_H
#define WASMEDGE_C_API_VM_H

#include "wasmedge/wasmedge_basic.h"
#include "wasmedge/wasmedge_value.h"

#ifdef __cplusplus
extern "C" {
#endif

// >>>>>>>> WasmEdge VM functions >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

/// Creation of the WasmEdge_VMContext.
///
/// The caller owns the object and should call `WasmEdge_VMDelete` to destroy
/// it.
///
/// \param ConfCxt the WasmEdge_ConfigureContext as the configuration of the VM.
/// NULL for the default configuration.
/// \param StoreCxt the WasmEdge_StoreContext as the external WASM store of the
/// VM. Instantiation and execution will refer to this store context, and the
/// lifetime should be guaranteed until the VM context is deleted. NULL for the
/// default store owned by `WasmEdge_VMContext`.
///
/// \returns pointer to context, NULL if failed.
WASMEDGE_CAPI_EXPORT extern WasmEdge_VMContext *
WasmEdge_VMCreate(const WasmEdge_ConfigureContext *ConfCxt,
                  WasmEdge_StoreContext *StoreCxt) WASMEDGE_CAPI_NOEXCEPT;

/// Register and instantiate WASM into the store in the VM from a WASM file.
///
/// Load a WASM file from the path, and register all exported instances and
/// instantiate them into the store in the VM with their exported name and
/// module name.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext that contains the store.
/// \param ModuleName the WasmEdge_String of module name for all exported
/// instances.
/// \param Path the NULL-terminated C string of the WASM file path.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result
WasmEdge_VMRegisterModuleFromFile(WasmEdge_VMContext *Cxt,
                                  const WasmEdge_String ModuleName,
                                  const char *Path) WASMEDGE_CAPI_NOEXCEPT;

/// Register and instantiate WASM into the store in the VM from a
/// WasmEdge_Bytes.
///
/// Load a WASM module from a WasmEdge_Bytes, and register all exported
/// instances and instantiate them into the store in the VM with their
/// exported name and module name.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext that contains the store.
/// \param ModuleName the WasmEdge_String of module name for all exported
/// instances.
/// \param Bytes the WasmEdge_Bytes of WASM binary.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result WasmEdge_VMRegisterModuleFromBytes(
    WasmEdge_VMContext *Cxt, const WasmEdge_String ModuleName,
    const WasmEdge_Bytes Bytes) WASMEDGE_CAPI_NOEXCEPT;

/// Instantiate and register an AST Module as a named module instance in the VM.
///
/// Load from the AST Module, and register all exported instances and
/// instantiate them in the store in the VM with their exported name and module
/// name.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext that contains the store.
/// \param ModuleName the WasmEdge_String of module name for all exported
/// instances.
/// \param ASTCxt the WasmEdge AST Module context generated by loader or
/// compiler.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result
WasmEdge_VMRegisterModuleFromASTModule(
    WasmEdge_VMContext *Cxt, const WasmEdge_String ModuleName,
    const WasmEdge_ASTModuleContext *ASTCxt) WASMEDGE_CAPI_NOEXCEPT;

/// Register a module instance in the store in the VM by exporting its module
/// name.
///
/// After calling this function, the existing module instance will be registered
/// in the store context in this VM, and the other modules can import the
/// exported instances for linking during instantiation. Developers SHOULD
/// guarantee the lifetime of this existing module instance, or an error will
/// occur during execution after the module instance is destroyed if it has
/// been imported by other modules. That is, developers should call the
/// `WasmEdge_ModuleInstanceDelete` if this existing module instance will no
/// longer be used or after the deletion of this VM. When the module instance is
/// deleted, it will be unregistered from the store context in this VM
/// automatically.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext that contains the store.
/// \param ImportCxt the WasmEdge_ModuleInstanceContext to register.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result WasmEdge_VMRegisterModuleFromImport(
    WasmEdge_VMContext *Cxt,
    const WasmEdge_ModuleInstanceContext *ImportCxt) WASMEDGE_CAPI_NOEXCEPT;

/// Register a module instance into the VM under the given alias name.
///
/// Similar to WasmEdge_VMRegisterModuleFromImport(), but registers the module
/// under the provided ModuleName instead of the module's own name.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param ModuleName the WasmEdge_String of module name to register as.
/// \param ImportCxt the WasmEdge_ModuleInstanceContext to register.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result
WasmEdge_VMRegisterModuleFromImportWithAlias(
    WasmEdge_VMContext *Cxt, const WasmEdge_String ModuleName,
    const WasmEdge_ModuleInstanceContext *ImportCxt) WASMEDGE_CAPI_NOEXCEPT;

/// Instantiate the WASM module from a WASM file and invoke a function by name.
///
/// Invoke a WASM function rapidly.
/// Load and instantiate the WASM module from the file path, and then invoke a
/// function by name and parameters. If the `Returns` buffer length is smaller
/// than the arity of the function, the overflowed return values will be
/// discarded.
/// After calling this function, a new anonymous module instance owned by the VM
/// is instantiated, and the old one will be destroyed.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param Path the NULL-terminated C string of the WASM file path.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
/// \param [out] Returns the WasmEdge_Value buffer to fill the return values.
/// \param ReturnLen the return buffer length.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result WasmEdge_VMRunWasmFromFile(
    WasmEdge_VMContext *Cxt, const char *Path, const WasmEdge_String FuncName,
    const WasmEdge_Value *Params, const uint32_t ParamLen,
    WasmEdge_Value *Returns, const uint32_t ReturnLen) WASMEDGE_CAPI_NOEXCEPT;

/// Instantiate the WASM module from a WasmEdge_Bytes and invoke a function by
/// name.
///
/// Invoke a WASM function rapidly.
/// Load and instantiate the WASM module from a WasmEdge_Bytes, and then invoke
/// a function by name and parameters. If the `Returns` buffer length is smaller
/// than the arity of the function, the overflowed return values will be
/// discarded.
/// After calling this function, a new anonymous module instance owned by the VM
/// is instantiated, and the old one will be destroyed.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param Bytes the WasmEdge_Bytes of WASM binary.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
/// \param [out] Returns the WasmEdge_Value buffer to fill the return values.
/// \param ReturnLen the return buffer length.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result
WasmEdge_VMRunWasmFromBytes(WasmEdge_VMContext *Cxt, const WasmEdge_Bytes Bytes,
                            const WasmEdge_String FuncName,
                            const WasmEdge_Value *Params,
                            const uint32_t ParamLen, WasmEdge_Value *Returns,
                            const uint32_t ReturnLen) WASMEDGE_CAPI_NOEXCEPT;

/// Instantiate the WASM module from a WasmEdge AST Module and invoke a function
/// by name.
///
/// Invoke a WASM function rapidly.
/// Load and instantiate the WASM module from the WasmEdge AST Module, and then
/// invoke the function by name and parameters. If the `Returns` buffer length
/// is smaller than the arity of the function, the overflowed return values will
/// be discarded.
/// After calling this function, a new anonymous module instance owned by the VM
/// is instantiated, and the old one will be destroyed.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param ASTCxt the WasmEdge AST Module context generated by loader or
/// compiler.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
/// \param [out] Returns the WasmEdge_Value buffer to fill the return values.
/// \param ReturnLen the return buffer length.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result WasmEdge_VMRunWasmFromASTModule(
    WasmEdge_VMContext *Cxt, const WasmEdge_ASTModuleContext *ASTCxt,
    const WasmEdge_String FuncName, const WasmEdge_Value *Params,
    const uint32_t ParamLen, WasmEdge_Value *Returns,
    const uint32_t ReturnLen) WASMEDGE_CAPI_NOEXCEPT;

/// Instantiate the WASM module from a WASM file and asynchronously invoke a
/// function by name.
///
/// Invoke a WASM function rapidly.
/// Load and instantiate the WASM module from the file path, and then invoke a
/// function by name and parameters. If the `Returns` buffer length is smaller
/// than the arity of the function, the overflowed return values will be
/// discarded.
/// After calling this function, a new anonymous module instance owned by the VM
/// is instantiated, and the old one will be destroyed.
///
/// The caller owns the object and should call `WasmEdge_AsyncDelete` to destroy
/// it.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param Path the NULL-terminated C string of the WASM file path.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
///
/// \returns WasmEdge_Async. Call `WasmEdge_AsyncGet` for the result, and call
/// `WasmEdge_AsyncDelete` to destroy this object.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Async *
WasmEdge_VMAsyncRunWasmFromFile(WasmEdge_VMContext *Cxt, const char *Path,
                                const WasmEdge_String FuncName,
                                const WasmEdge_Value *Params,
                                const uint32_t ParamLen) WASMEDGE_CAPI_NOEXCEPT;

/// Instantiate the WASM module from a WasmEdge_Bytes and asynchronously invoke
/// a function by name.
///
/// Invoke a WASM function rapidly.
/// Load and instantiate the WASM module from a WasmEdge_Bytes, and then invoke
/// a function by name and parameters. If the `Returns` buffer length is smaller
/// than the arity of the function, the overflowed return values will be
/// discarded.
/// After calling this function, a new anonymous module instance owned by the VM
/// is instantiated, and the old one will be destroyed.
///
/// The caller owns the object and should call `WasmEdge_AsyncDelete` to destroy
/// it.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param Bytes the WasmEdge_Bytes of WASM binary.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
///
/// \returns WasmEdge_Async. Call `WasmEdge_AsyncGet` for the result, and call
/// `WasmEdge_AsyncDelete` to destroy this object.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Async *WasmEdge_VMAsyncRunWasmFromBytes(
    WasmEdge_VMContext *Cxt, const WasmEdge_Bytes Bytes,
    const WasmEdge_String FuncName, const WasmEdge_Value *Params,
    const uint32_t ParamLen) WASMEDGE_CAPI_NOEXCEPT;

/// Instantiate the WASM module from a WasmEdge AST Module and asynchronously
/// invoke a function by name.
///
/// Invoke a WASM function rapidly.
/// Load and instantiate the WASM module from the WasmEdge AST Module, and then
/// invoke the function by name and parameters. If the `Returns` buffer length
/// is smaller than the arity of the function, the overflowed return values will
/// be discarded.
/// After calling this function, a new anonymous module instance owned by the VM
/// is instantiated, and the old one will be destroyed.
///
/// The caller owns the object and should call `WasmEdge_AsyncDelete` to destroy
/// it.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param ASTCxt the WasmEdge AST Module context generated by loader or
/// compiler.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
///
/// \returns WasmEdge_Async. Call `WasmEdge_AsyncGet` for the result, and call
/// `WasmEdge_AsyncDelete` to destroy this object.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Async *
WasmEdge_VMAsyncRunWasmFromASTModule(
    WasmEdge_VMContext *Cxt, const WasmEdge_ASTModuleContext *ASTCxt,
    const WasmEdge_String FuncName, const WasmEdge_Value *Params,
    const uint32_t ParamLen) WASMEDGE_CAPI_NOEXCEPT;

/// Load the WASM module from a WASM file.
///
/// This is the first step for step-by-step WASM function invocation.
/// Load and parse the WASM module from the file path. You can then call
/// `WasmEdge_VMValidate` for the next step.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param Path the NULL-terminated C string of the WASM file path.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result
WasmEdge_VMLoadWasmFromFile(WasmEdge_VMContext *Cxt,
                            const char *Path) WASMEDGE_CAPI_NOEXCEPT;

/// Load the WASM module from a WasmEdge_Bytes.
///
/// This is the first step for step-by-step WASM function invocation.
/// Load and parse the WASM module from a WasmEdge_Bytes. You can then call
/// `WasmEdge_VMValidate` for the next step.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param Bytes the WasmEdge_Bytes of WASM binary.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result
WasmEdge_VMLoadWasmFromBytes(WasmEdge_VMContext *Cxt,
                             const WasmEdge_Bytes Bytes) WASMEDGE_CAPI_NOEXCEPT;

/// Load the WASM module from loaded WasmEdge AST Module.
///
/// This is the first step for step-by-step WASM function invocation.
/// Copy the loaded WasmEdge AST Module context into the VM. The VM context has
/// no dependency on the input AST Module context. You can then call
/// `WasmEdge_VMValidate` for the next step.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param ASTCxt the WasmEdge AST Module context generated by loader or
/// compiler.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result WasmEdge_VMLoadWasmFromASTModule(
    WasmEdge_VMContext *Cxt,
    const WasmEdge_ASTModuleContext *ASTCxt) WASMEDGE_CAPI_NOEXCEPT;

/// Validate the WASM module loaded into the VM context.
///
/// This is the second step for step-by-step WASM function invocation.
/// After loading a WASM module into the VM context, you can call this function
/// to validate it. You can then call `WasmEdge_VMInstantiate` for the next
/// step. Note that only validated WASM modules can be instantiated in the VM
/// context.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result
WasmEdge_VMValidate(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Instantiate the validated WASM module in the VM context.
///
/// This is the third step for step-by-step WASM function invocation.
/// After validating a WASM module in the VM context, you can call this function
/// to instantiate it. You can then call `WasmEdge_VMExecute` to invoke
/// the exported function in this WASM module.
/// After calling this function, a new anonymous module instance owned by the VM
/// is instantiated, and the old one will be destroyed.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result
WasmEdge_VMInstantiate(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Invoke a WASM function by name.
///
/// This is the final step for step-by-step WASM function invocation.
/// After instantiating a WASM module in the VM context, the WASM module is
/// registered in the store in the VM context as an anonymous module. Then you
/// can repeatedly call this function to invoke the exported WASM functions by
/// their names until the VM context is reset or a new WASM module is registered
/// or loaded. For calling the functions in registered WASM modules with module
/// names, please use `WasmEdge_VMExecuteRegistered` instead. If the `Returns`
/// buffer length is smaller than the arity of the function, the overflowed
/// return values will be discarded. Note that a discarded GC reference result
/// is still retained as a collector root (see `WasmEdge_VMReleaseRef`) yet
/// never handed back to the caller, so it can then only be freed via
/// `WasmEdge_VMReleaseAllRefs`; pass a buffer large enough for the full arity
/// to keep returned GC references individually releasable.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
/// \param [out] Returns the WasmEdge_Value buffer to fill the return values.
/// \param ReturnLen the return buffer length.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result
WasmEdge_VMExecute(WasmEdge_VMContext *Cxt, const WasmEdge_String FuncName,
                   const WasmEdge_Value *Params, const uint32_t ParamLen,
                   WasmEdge_Value *Returns,
                   const uint32_t ReturnLen) WASMEDGE_CAPI_NOEXCEPT;

/// Invoke a WASM function by its module name and function name.
///
/// After registering a WASM module in the VM context, you can repeatedly call
/// this function to invoke exported WASM functions by their module names and
/// function names until the VM context is reset. If the `Returns` buffer length
/// is smaller than the arity of the function, the overflowed return values will
/// be discarded. As with `WasmEdge_VMExecute`, a discarded GC reference result
/// stays retained as a collector root and can then only be freed via
/// `WasmEdge_VMReleaseAllRefs` (see `WasmEdge_VMReleaseRef`).
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param ModuleName the module name WasmEdge_String.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
/// \param [out] Returns the WasmEdge_Value buffer to fill the return values.
/// \param ReturnLen the return buffer length.
///
/// \returns WasmEdge_Result. Call `WasmEdge_ResultGetMessage` for the error
/// message.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Result WasmEdge_VMExecuteRegistered(
    WasmEdge_VMContext *Cxt, const WasmEdge_String ModuleName,
    const WasmEdge_String FuncName, const WasmEdge_Value *Params,
    const uint32_t ParamLen, WasmEdge_Value *Returns,
    const uint32_t ReturnLen) WASMEDGE_CAPI_NOEXCEPT;

/// Asynchronously invoke a WASM function by name.
///
/// This is the final step for step-by-step WASM function invocation.
/// After instantiating a WASM module in the VM context, the WASM module is
/// registered in the store in the VM context as an anonymous module. Then you
/// can repeatedly call this function to invoke the exported WASM functions by
/// their names until the VM context is reset or a new WASM module is registered
/// or loaded. For calling the functions in registered WASM modules with module
/// names, please use `WasmEdge_VMAsyncExecuteRegistered` instead.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
///
/// \returns WasmEdge_Async. Call `WasmEdge_AsyncGet` for the result, and call
/// `WasmEdge_AsyncDelete` to destroy this object.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Async *
WasmEdge_VMAsyncExecute(WasmEdge_VMContext *Cxt, const WasmEdge_String FuncName,
                        const WasmEdge_Value *Params,
                        const uint32_t ParamLen) WASMEDGE_CAPI_NOEXCEPT;

/// Asynchronously invoke a WASM function by its module name and function name.
///
/// After registering a WASM module in the VM context, you can repeatedly call
/// this function to invoke exported WASM functions by their module names and
/// function names until the VM context is reset.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param ModuleName the module name WasmEdge_String.
/// \param FuncName the function name WasmEdge_String.
/// \param Params the WasmEdge_Value buffer with the parameter values.
/// \param ParamLen the parameter buffer length.
///
/// \returns WasmEdge_Async. Call `WasmEdge_AsyncGet` for the result, and call
/// `WasmEdge_AsyncDelete` to destroy this object.
WASMEDGE_CAPI_EXPORT extern WasmEdge_Async *WasmEdge_VMAsyncExecuteRegistered(
    WasmEdge_VMContext *Cxt, const WasmEdge_String ModuleName,
    const WasmEdge_String FuncName, const WasmEdge_Value *Params,
    const uint32_t ParamLen) WASMEDGE_CAPI_NOEXCEPT;

/// Get the function type by function name.
///
/// After instantiating a WASM module in the VM context, the WASM module is
/// registered in the store in the VM context as an anonymous module. Then you
/// can call this function to get the function type by the exported function
/// name until the VM context is reset or a new WASM module is registered or
/// loaded. For getting the function type of functions in registered WASM
/// modules with module names, please use `WasmEdge_VMGetFunctionTypeRegistered`
/// instead.
/// The returned function type contexts are linked to the context owned by the
/// VM context, and the caller should __NOT__ call the
/// `WasmEdge_FunctionTypeDelete` to destroy it.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param FuncName the function name WasmEdge_String.
///
/// \returns the function type. NULL if the function is not found.
WASMEDGE_CAPI_EXPORT extern const WasmEdge_FunctionTypeContext *
WasmEdge_VMGetFunctionType(const WasmEdge_VMContext *Cxt,
                           const WasmEdge_String FuncName)
    WASMEDGE_CAPI_NOEXCEPT;

/// Get the function type by function name.
///
/// After registering a WASM module in the VM context, you can call this
/// function to get the function type by the functions' exported module names
/// and function names until the VM context is reset.
/// The returned function type contexts are linked to the context owned by the
/// VM context, and the caller should __NOT__ call the
/// `WasmEdge_FunctionTypeDelete` to destroy it.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param ModuleName the module name WasmEdge_String.
/// \param FuncName the function name WasmEdge_String.
///
/// \returns the function type. NULL if the function is not found.
WASMEDGE_CAPI_EXPORT extern const WasmEdge_FunctionTypeContext *
WasmEdge_VMGetFunctionTypeRegistered(
    const WasmEdge_VMContext *Cxt, const WasmEdge_String ModuleName,
    const WasmEdge_String FuncName) WASMEDGE_CAPI_NOEXCEPT;

/// Reset of WasmEdge_VMContext.
///
/// After calling this function, the statistics, loaded module, the instantiated
/// instances, and the registered instances except the WASI and plug-ins will
/// all be cleared.
///
/// This does NOT release the host-retained GC reference set: any GC (struct or
/// array) reference previously returned to the host survives cleanup, but the
/// module-instance pointer it embeds dangles once the instances above are torn
/// down. Release such references first (`WasmEdge_VMReleaseRef` /
/// `WasmEdge_VMReleaseAllRefs`) if the host keeps using them across cleanup.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext to reset.
WASMEDGE_CAPI_EXPORT extern void
WasmEdge_VMCleanup(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Release a host-retained GC reference returned by the VM.
///
/// When a function returns a GC-managed (struct/array) reference to the host,
/// the runtime retains it as a GC root so the collector keeps it alive. Call
/// this to release one such reference when the host no longer needs it.
///
/// The `Ref` should be a value previously returned as a function result. Values
/// whose heap type is not struct/array (funcref/externref/i31ref/null) are not
/// retained roots and are silently skipped, so passing any non-result or
/// non-struct/array value is a no-op.
///
/// KNOWN LIMITATION: a struct/array reference that has been externalized
/// (`extern.convert_any`) is retained as a root but handed to the host typed as
/// `externref`. Because this function matches on the visible heap type, such a
/// value is treated as non-struct/array and skipped here; it can therefore only
/// be freed via `WasmEdge_VMReleaseAllRefs`, not released individually.
///
/// Unreleased references survive WasmEdge_VMCleanup, which does NOT release the
/// host-root set; however, the leading module-instance pointer those references
/// embed dangles once the instances are torn down. To avoid this, call
/// WasmEdge_VMReleaseAllRefs (or release each reference) around cleanup.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param Ref the reference value to release.
WASMEDGE_CAPI_EXPORT extern void
WasmEdge_VMReleaseRef(WasmEdge_VMContext *Cxt,
                      const WasmEdge_Value Ref) WASMEDGE_CAPI_NOEXCEPT;

/// Release several host-retained GC references returned by the VM.
///
/// Passing a null `Refs` or zero `Len` is a no-op. Each entry is released
/// independently: entries that are not retained struct/array roots are silently
/// skipped, and if the same reference appears multiple times in `Refs` each
/// occurrence releases one retained instance.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param Refs array of reference values to release.
/// \param Len length of the `Refs` array.
WASMEDGE_CAPI_EXPORT extern void
WasmEdge_VMReleaseRefs(WasmEdge_VMContext *Cxt, const WasmEdge_Value *Refs,
                       const uint32_t Len) WASMEDGE_CAPI_NOEXCEPT;

/// Release all host-retained GC references held by the VM.
///
/// After this call, all GC reference values previously returned to the host
/// become invalid. Because the host-root set is shared across threads, this
/// invalidates such references for every thread, not only the caller's.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
WASMEDGE_CAPI_EXPORT extern void
WasmEdge_VMReleaseAllRefs(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Get the length of exported function list.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns length of exported function list.
WASMEDGE_CAPI_EXPORT extern uint32_t WasmEdge_VMGetFunctionListLength(
    const WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Get the exported function list.
///
/// The returned function names stored in the `Names` array link to the
/// exported names of functions owned by the vm context, and the caller should
/// __NOT__ call the `WasmEdge_StringDelete` to destroy them.
/// The function type contexts stored in the `FuncTypes` array of the
/// corresponding function names link to the context owned by the VM context.
/// The caller should __NOT__ call the `WasmEdge_FunctionTypeDelete` to destroy
/// them.
/// If the `Names` and `FuncTypes` buffer lengths are smaller than the result of
/// the exported function list size, the overflowed return values will be
/// discarded.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param [out] Names the output names WasmEdge_String buffer of exported
/// functions. Can be NULL if names are not needed.
/// \param [out] FuncTypes the function type contexts buffer. Can be NULL if
/// function types are not needed.
/// \param Len the buffer length.
///
/// \returns actual exported function list size.
WASMEDGE_CAPI_EXPORT extern uint32_t
WasmEdge_VMGetFunctionList(const WasmEdge_VMContext *Cxt,
                           WasmEdge_String *Names,
                           const WasmEdge_FunctionTypeContext **FuncTypes,
                           const uint32_t Len) WASMEDGE_CAPI_NOEXCEPT;

/// Unregister and trigger the deletion of a registered module from the VM.
///
/// This function unregisters the module with the given name from the VM.
/// The module will be safely destroyed only when there are no remaining
/// dependencies from other modules
///
/// \param Cxt the WasmEdge_VMContext to delete the module from.
/// \param ModuleName the name of the module to delete.
WASMEDGE_CAPI_EXPORT extern void WasmEdge_VMDeleteRegisteredModule(
    const WasmEdge_VMContext *Cxt,
    const WasmEdge_String ModuleName) WASMEDGE_CAPI_NOEXCEPT;

/// Get the module instance corresponding to the WasmEdge_HostRegistration
/// settings.
///
/// When creating the VM context with a configuration, the built-in host module
/// will be registered according to the `WasmEdge_HostRegistration` settings
/// added to the `WasmEdge_ConfigureContext`. You can call this function to
/// get the `WasmEdge_ModuleInstanceContext` corresponding to the settings. The
/// module instance context links to the context owned by the VM context. The
/// caller should __NOT__ call the `WasmEdge_ModuleInstanceDelete`.
///
/// ```c
/// WasmEdge_ConfigureContext *Conf = WasmEdge_ConfigureCreate();
/// WasmEdge_ConfigureAddHostRegistration(Conf, WasmEdge_HostRegistration_Wasi);
/// WasmEdge_VMContext *VM = WasmEdge_VMCreate(Conf, NULL);
/// WasmEdge_ModuleInstanceContext *WasiMod =
///     WasmEdge_VMGetImportModuleContext(VM, WasmEdge_HostRegistration_Wasi);
/// ```
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param Reg the host registration value to get the import module.
///
/// \returns pointer to the module instance context. NULL if not found.
WASMEDGE_CAPI_EXPORT extern WasmEdge_ModuleInstanceContext *
WasmEdge_VMGetImportModuleContext(const WasmEdge_VMContext *Cxt,
                                  const enum WasmEdge_HostRegistration Reg)
    WASMEDGE_CAPI_NOEXCEPT;

/// Get the current instantiated module in the VM.
///
/// After instantiating a module instance in the VM, developers can call this
/// API to get the active anonymous module instance to retrieve the exported
/// instances. The module instance context links to the context owned by the VM
/// context. The caller should __NOT__ call the `WasmEdge_ModuleInstanceDelete`.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns pointer to the module instance context. NULL if not found.
WASMEDGE_CAPI_EXPORT extern const WasmEdge_ModuleInstanceContext *
WasmEdge_VMGetActiveModule(const WasmEdge_VMContext *Cxt)
    WASMEDGE_CAPI_NOEXCEPT;

/// Get the registered module in the VM by module name.
///
/// After registering a WASM module in the VM context, developers can call
/// this function to get the module instance by the module name. The returned
/// module instance context links to the context owned by the VM context, and
/// the caller should __NOT__ call the `WasmEdge_ModuleInstanceDelete` to
/// destroy it.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param ModuleName the module name WasmEdge_String.
///
/// \returns pointer to the module instance context. NULL if not found.
WASMEDGE_CAPI_EXPORT extern const WasmEdge_ModuleInstanceContext *
WasmEdge_VMGetRegisteredModule(const WasmEdge_VMContext *Cxt,
                               const WasmEdge_String ModuleName)
    WASMEDGE_CAPI_NOEXCEPT;

/// Get the length of registered module list in the WasmEdge_VMContext.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns length of registered module list.
WASMEDGE_CAPI_EXPORT extern uint32_t WasmEdge_VMListRegisteredModuleLength(
    const WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// List the registered module names in the WasmEdge_VMContext.
///
/// This function will list all registered module names.
/// The returned module names stored in the `Names` array are linked to the
/// registered module names in the VM context, and the caller should __NOT__
/// call the `WasmEdge_StringDelete`.
/// If the `Names` buffer length is smaller than the result of the registered
/// named module list size, the overflowed return values will be discarded.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
/// \param [out] Names the output names WasmEdge_String buffer of the registered
/// modules.
/// \param Len the buffer length.
///
/// \returns actual registered module list size.
WASMEDGE_CAPI_EXPORT extern uint32_t
WasmEdge_VMListRegisteredModule(const WasmEdge_VMContext *Cxt,
                                WasmEdge_String *Names,
                                const uint32_t Len) WASMEDGE_CAPI_NOEXCEPT;

/// Get the store context used in the WasmEdge_VMContext.
///
/// The returned store context links to the store in the VM context and is owned
/// by the VM context. This function will return NULL if an error occurs. The
/// caller should __NOT__ call the `WasmEdge_StoreDelete`.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns pointer to the store context.
WASMEDGE_CAPI_EXPORT extern WasmEdge_StoreContext *
WasmEdge_VMGetStoreContext(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Get the loader context used in the WasmEdge_VMContext.
///
/// The returned loader context links to the loader in the VM context and is
/// owned by the VM context. This function will return NULL if an error occurs.
/// The caller should __NOT__ call the `WasmEdge_LoaderDelete`.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns pointer to the loader context.
WASMEDGE_CAPI_EXPORT extern WasmEdge_LoaderContext *
WasmEdge_VMGetLoaderContext(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Get the validator context used in the WasmEdge_VMContext.
///
/// The returned validator context links to the validator in the VM context and
/// is owned by the VM context. This function will return NULL if an error
/// occurs. The caller should __NOT__ call the `WasmEdge_ValidatorDelete`.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns pointer to the validator context.
WASMEDGE_CAPI_EXPORT extern WasmEdge_ValidatorContext *
WasmEdge_VMGetValidatorContext(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Get the executor context used in the WasmEdge_VMContext.
///
/// The returned executor context links to the executor in the VM context and is
/// owned by the VM context. This function will return NULL if an error occurs.
/// The caller should __NOT__ call the `WasmEdge_ExecutorDelete`.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns pointer to the executor context.
WASMEDGE_CAPI_EXPORT extern WasmEdge_ExecutorContext *
WasmEdge_VMGetExecutorContext(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Get the statistics context used in the WasmEdge_VMContext.
///
/// The statistics context links to the statistics in the VM context and owned
/// by the VM context. The caller should __NOT__ call the
/// `WasmEdge_StatisticsDelete`.
///
/// This function is thread-safe.
///
/// \param Cxt the WasmEdge_VMContext.
///
/// \returns pointer to the statistics context.
WASMEDGE_CAPI_EXPORT extern WasmEdge_StatisticsContext *
WasmEdge_VMGetStatisticsContext(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

/// Deletion of the WasmEdge_VMContext.
///
/// After calling this function, the context will be destroyed and should
/// __NOT__ be used.
///
/// \param Cxt the WasmEdge_VMContext to destroy.
WASMEDGE_CAPI_EXPORT extern void
WasmEdge_VMDelete(WasmEdge_VMContext *Cxt) WASMEDGE_CAPI_NOEXCEPT;

// <<<<<<<< WasmEdge VM functions <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#ifdef __cplusplus
} /// extern "C"
#endif

#endif /// WASMEDGE_C_API_VM_H
