/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_WasmEdge_LogLevel */

#ifndef _Included_org_wasmedge_WasmEdge_LogLevel
#define _Included_org_wasmedge_WasmEdge_LogLevel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
