/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_WasmEdgeResult */

#ifndef _Included_org_wasmedge_WasmEdgeResult
#define _Included_org_wasmedge_WasmEdgeResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_WasmEdgeResult
 * Method:    getResultCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wasmedge_WasmEdgeResult_getResultCode
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeResult
 * Method:    isOk
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wasmedge_WasmEdgeResult_isOk
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeResult
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wasmedge_WasmEdgeResult_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
