/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_WasmEdgeString */

#ifndef _Included_org_wasmedge_WasmEdgeString
#define _Included_org_wasmedge_WasmEdgeString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_WasmEdgeString
 * Method:    createInternal
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_WasmEdgeString_createInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_WasmEdgeString
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_WasmEdgeString_delete
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeString
 * Method:    toStringInternal
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wasmedge_WasmEdgeString_toStringInternal
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeString
 * Method:    equalsInternal
 * Signature: (Lorg/wasmedge/WasmEdgeString;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wasmedge_WasmEdgeString_equalsInternal
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
