/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_WasmEdgeVM */

#ifndef _Included_org_wasmedge_WasmEdgeVM
#define _Included_org_wasmedge_WasmEdgeVM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_WasmEdgeVM
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wasmedge_WasmEdgeVM_getVersion
  (JNIEnv * env, jobject thisObject);

/*
 * Class:     org_wasmedge_WasmEdgeVM
 * Method:    getMajorVersion
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wasmedge_WasmEdgeVM_getMajorVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeVM
 * Method:    getMinorVersion
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wasmedge_WasmEdgeVM_getMinorVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeVM
 * Method:    getPatchVersion
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wasmedge_WasmEdgeVM_getPatchVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
