function(wasmedge_cmake_cache_argument Output Name Type Value)
  string(REPLACE ";" "\\;" Value "${Value}")
  set(${Output} "-D${Name}:${Type}=${Value}" PARENT_SCOPE)
endfunction()

function(wasmedge_read_cmake_cache_value Output CacheFile Name Type)
  file(READ "${CacheFile}" Cache)
  string(REGEX MATCH "(^|\n)${Name}:${Type}=([^\n\r]*)" Match "${Cache}")
  if(NOT Match)
    message(FATAL_ERROR "${Name}:${Type} is missing from ${CacheFile}")
  endif()
  set(Value "${CMAKE_MATCH_2}")
  string(REPLACE "\\;" ";" Value "${Value}")
  set(${Output} "${Value}" PARENT_SCOPE)
endfunction()
