/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_VMContext */

#ifndef _Included_org_wasmedge_VMContext
#define _Included_org_wasmedge_VMContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_VMContext
 * Method:    initNative
 * Signature: (Lorg/wasmedge/ConfigureContext;Lorg/wasmedge/StoreContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_VMContext_initNative
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_wasmedge_VMContext
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_VMContext_cleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
