/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_GlobalInstanceContext */

#ifndef _Included_org_wasmedge_GlobalInstanceContext
#define _Included_org_wasmedge_GlobalInstanceContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_GlobalInstanceContext
 * Method:    nativeInit
 * Signature: (Lorg/wasmedge/GlobalTypeContext;Lorg/wasmedge/WasmEdgeValue;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_GlobalInstanceContext_nativeInit
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_wasmedge_GlobalInstanceContext
 * Method:    nativeSetValue
 * Signature: (Lorg/wasmedge/WasmEdgeValue;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_GlobalInstanceContext_nativeSetValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_GlobalInstanceContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_GlobalInstanceContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
