/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_ValidatorContext */

#ifndef _Included_org_wasmedge_ValidatorContext
#define _Included_org_wasmedge_ValidatorContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_ValidatorContext
 * Method:    validate
 * Signature: (Lorg/wasmedge/ASTModuleContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ValidatorContext_validate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_ValidatorContext
 * Method:    nativeInit
 * Signature: (Lorg/wasmedge/ConfigureContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ValidatorContext_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_ValidatorContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ValidatorContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
