/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_StoreContext */

#ifndef _Included_org_wasmedge_StoreContext
#define _Included_org_wasmedge_StoreContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_StoreContext
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_StoreContext_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_StoreContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
