/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_TableTypeContext */

#ifndef _Included_org_wasmedge_TableTypeContext
#define _Included_org_wasmedge_TableTypeContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_TableTypeContext
 * Method:    nativeInit
 * Signature: (ILorg/wasmedge/WasmEdgeLimit;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_TableTypeContext_nativeInit
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_wasmedge_TableTypeContext
 * Method:    getLimit
 * Signature: ()Lorg/wasmedge/WasmEdgeLimit;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_TableTypeContext_getLimit
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_TableTypeContext
 * Method:    nativeGetRefType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wasmedge_TableTypeContext_nativeGetRefType
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_TableTypeContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_TableTypeContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
