/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_FunctionInstanceContext */

#ifndef _Included_org_wasmedge_FunctionInstanceContext
#define _Included_org_wasmedge_FunctionInstanceContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_FunctionInstanceContext
 * Method:    nativeCreateFunction
 * Signature: (Lorg/wasmedge/FunctionTypeContext;Lorg/wasmedge/HostFunction;Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_FunctionInstanceContext_nativeCreateFunction
  (JNIEnv *, jobject, jobject, jobject, jobject, jlong);

/*
 * Class:     org_wasmedge_FunctionInstanceContext
 * Method:    nativeCreateBinding
 * Signature: (Lorg/wasmedge/FunctionTypeContext;Lorg/wasmedge/WrapFunction;Ljava/lang/Object;Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_FunctionInstanceContext_nativeCreateBinding
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jlong);

/*
 * Class:     org_wasmedge_FunctionInstanceContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_FunctionInstanceContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
