/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_FunctionInstanceContext */

#ifndef _Included_org_wasmedge_FunctionInstanceContext
#define _Included_org_wasmedge_FunctionInstanceContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_FunctionInstanceContext
 * Method:    getFunctionType
 * Signature: ()Lorg/wasmedge/FunctionTypeContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_FunctionInstanceContext_getFunctionType
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_FunctionInstanceContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_FunctionInstanceContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
