/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_StatisticsContext */

#ifndef _Included_org_wasmedge_StatisticsContext
#define _Included_org_wasmedge_StatisticsContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_StatisticsContext
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_StatisticsContext_nativeInit
        (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StatisticsContext
 * Method:    getInstrCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wasmedge_StatisticsContext_getInstrCount
        (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StatisticsContext
 * Method:    getInstrPerSecond
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wasmedge_StatisticsContext_getInstrPerSecond
        (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StatisticsContext
 * Method:    setCostTable
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_StatisticsContext_setCostTable
        (JNIEnv *, jobject, jlongArray);

/*
 * Class:     org_wasmedge_StatisticsContext
 * Method:    setCostLimit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_StatisticsContext_setCostLimit
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wasmedge_StatisticsContext
 * Method:    getTotalCost
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wasmedge_StatisticsContext_getTotalCost
        (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StatisticsContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_StatisticsContext_delete
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
