/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_TableInstanceContext */

#ifndef _Included_org_wasmedge_TableInstanceContext
#define _Included_org_wasmedge_TableInstanceContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_TableInstanceContext
 * Method:    nativeInit
 * Signature: (Lorg/wasmedge/TableTypeContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_TableInstanceContext_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_TableInstanceContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_TableInstanceContext_delete
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_TableInstanceContext
 * Method:    setData
 * Signature: (Lorg/wasmedge/WasmEdgeValue;I)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_TableInstanceContext_setData
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_wasmedge_TableInstanceContext
 * Method:    getData
 * Signature: (Lorg/wasmedge/enums/ValueType;I)Lorg/wasmedge/WasmEdgeValue;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_TableInstanceContext_getData
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_wasmedge_TableInstanceContext
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wasmedge_TableInstanceContext_getSize
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_TableInstanceContext
 * Method:    grow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_TableInstanceContext_grow
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
