/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_WasmEdgeVM */

#ifndef _Included_org_wasmedge_WasmEdgeVM
#define _Included_org_wasmedge_WasmEdgeVM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_WasmEdgeVM
 * Method:    runWasmFromFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Lorg/wasmedge/WasmEdgeValue;I[I[Lorg/wasmedge/WasmEdgeValue;I[I)Lorg/wasmedge/WasmEdgeResult;
 */
JNIEXPORT void JNICALL Java_org_wasmedge_WasmEdgeVM_runWasmFromFile
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jint, jintArray, jobjectArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
