/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_ImportObjectContext */

#ifndef _Included_org_wasmedge_ImportObjectContext
#define _Included_org_wasmedge_ImportObjectContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ImportObjectContext_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    initWASI
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ImportObjectContext_initWASI
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    getWASIExitCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wasmedge_ImportObjectContext_getWASIExitCode
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    createWasmEdgeProcess
 * Signature: ([Ljava/lang/String;Z)Lorg/wasmedge/ImportObjectContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ImportObjectContext_createWasmEdgeProcess
  (JNIEnv *, jclass, jobjectArray, jboolean);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    initWasmEdgeProcess
 * Signature: ([Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ImportObjectContext_initWasmEdgeProcess
  (JNIEnv *, jobject, jobjectArray, jboolean);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    addFunction
 * Signature: (Ljava/lang/String;Lorg/wasmedge/FunctionInstanceContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ImportObjectContext_addFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    addTable
 * Signature: (Ljava/lang/String;Lorg/wasmedge/TableInstanceContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ImportObjectContext_addTable
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    addMemory
 * Signature: (Ljava/lang/String;Lorg/wasmedge/MemoryInstanceContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ImportObjectContext_addMemory
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    addGlobal
 * Signature: (Ljava/lang/String;Lorg/wasmedge/GlobalInstanceContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ImportObjectContext_addGlobal
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ImportObjectContext_delete
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ImportObjectContext
 * Method:    CreateWASI
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Lorg/wasmedge/ImportObjectContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ImportObjectContext_CreateWASI
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
