/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_ModuleInstanceContext */

#ifndef _Included_org_wasmedge_ModuleInstanceContext
#define _Included_org_wasmedge_ModuleInstanceContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    createWasmEdgeProcess
 * Signature: ([Ljava/lang/String;Z)Lorg/wasmedge/ModuleInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_createWasmEdgeProcess
  (JNIEnv *, jclass, jobjectArray, jboolean);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    CreateWASI
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Lorg/wasmedge/ModuleInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_CreateWASI
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ModuleInstanceContext_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    initWASI
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ModuleInstanceContext_initWASI
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    getWASIExitCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wasmedge_ModuleInstanceContext_getWASIExitCode
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    initWasmEdgeProcess
 * Signature: ([Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ModuleInstanceContext_initWasmEdgeProcess
  (JNIEnv *, jobject, jobjectArray, jboolean);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    addFunction
 * Signature: (Ljava/lang/String;Lorg/wasmedge/FunctionInstanceContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ModuleInstanceContext_addFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    addTable
 * Signature: (Ljava/lang/String;Lorg/wasmedge/TableInstanceContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ModuleInstanceContext_addTable
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    addMemory
 * Signature: (Ljava/lang/String;Lorg/wasmedge/MemoryInstanceContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ModuleInstanceContext_addMemory
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    addGlobal
 * Signature: (Ljava/lang/String;Lorg/wasmedge/GlobalInstanceContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ModuleInstanceContext_addGlobal
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    listFunction
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_listFunction
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    findFunction
 * Signature: (Ljava/lang/String;)Lorg/wasmedge/FunctionInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_findFunction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    listTable
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_listTable
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    findTable
 * Signature: (Ljava/lang/String;)Lorg/wasmedge/TableInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_findTable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    listMemory
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_listMemory
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    findMemory
 * Signature: (Ljava/lang/String;)Lorg/wasmedge/MemoryInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_findMemory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    listGlobal
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_listGlobal
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    findGlobal
 * Signature: (Ljava/lang/String;)Lorg/wasmedge/GlobalInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ModuleInstanceContext_findGlobal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_ModuleInstanceContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ModuleInstanceContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
