/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_StoreContext */

#ifndef _Included_org_wasmedge_StoreContext
#define _Included_org_wasmedge_StoreContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_StoreContext
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_StoreContext_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_StoreContext_delete
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    findFunction
 * Signature: (Ljava/lang/String;)Lorg/wasmedge/FunctionInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_findFunction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    findFunctionRegistered
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/wasmedge/FunctionInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_findFunctionRegistered
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    findTable
 * Signature: (Ljava/lang/String;)Lorg/wasmedge/TableInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_findTable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    findTableRegistered
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/wasmedge/TableInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_findTableRegistered
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    findMemory
 * Signature: (Ljava/lang/String;)Lorg/wasmedge/MemoryInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_findMemory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    findMemoryRegistered
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/wasmedge/MemoryInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_findMemoryRegistered
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    findGlobal
 * Signature: (Ljava/lang/String;)Lorg/wasmedge/GlobalInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_findGlobal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    findGlobalRegistered
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/wasmedge/GlobalInstanceContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_findGlobalRegistered
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    listFunction
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_listFunction
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    listFunctionRegistered
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_listFunctionRegistered
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    listTable
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_listTable
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    listTableRegistered
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_listTableRegistered
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    listMemory
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_listMemory
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    listMemoryRegistered
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_listMemoryRegistered
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    listGlobal
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_listGlobal
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    listGlobalRegistered
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_listGlobalRegistered
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_StoreContext
 * Method:    listModule
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_StoreContext_listModule
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
