/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_WasmEdgeAsync */

#ifndef _Included_org_wasmedge_WasmEdgeAsync
#define _Included_org_wasmedge_WasmEdgeAsync
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_WasmEdgeAsync
 * Method:    wasmEdge_AsyncWait
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_WasmEdgeAsync_wasmEdge_1AsyncWait
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeAsync
 * Method:    wasmEdge_AsyncWaitFor
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wasmedge_WasmEdgeAsync_wasmEdge_1AsyncWaitFor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wasmedge_WasmEdgeAsync
 * Method:    wasmEdge_AsyncCancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_WasmEdgeAsync_wasmEdge_1AsyncCancel
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeAsync
 * Method:    wasmEdge_AsyncGetReturnsLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wasmedge_WasmEdgeAsync_wasmEdge_1AsyncGetReturnsLength
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeAsync
 * Method:    wasmEdge_AsyncGet
 * Signature: (Lorg/wasmedge/WasmEdgeValue;I)Lorg/wasmedge/Result;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_WasmEdgeAsync_wasmEdge_1AsyncGet
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_wasmedge_WasmEdgeAsync
 * Method:    wasmEdge_AsyncDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_WasmEdgeAsync_wasmEdge_1AsyncDelete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
