/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_ExportTypeContext */

#ifndef _Included_org_wasmedge_ExportTypeContext
#define _Included_org_wasmedge_ExportTypeContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_ExportTypeContext
 * Method:    getModuleName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wasmedge_ExportTypeContext_getModuleName
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ExportTypeContext
 * Method:    getExternalName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wasmedge_ExportTypeContext_getExternalName
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ExportTypeContext
 * Method:    nativeGetExternalType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wasmedge_ExportTypeContext_nativeGetExternalType
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ExportTypeContext
 * Method:    nativeGetFunctionType
 * Signature: (Lorg/wasmedge/ASTModuleContext;)Lorg/wasmedge/FunctionTypeContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ExportTypeContext_nativeGetFunctionType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_ExportTypeContext
 * Method:    nativeGetTableType
 * Signature: (Lorg/wasmedge/ASTModuleContext;)Lorg/wasmedge/TableTypeContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ExportTypeContext_nativeGetTableType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_ExportTypeContext
 * Method:    nativeGetMemoryType
 * Signature: (Lorg/wasmedge/ASTModuleContext;)Lorg/wasmedge/MemoryTypeContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ExportTypeContext_nativeGetMemoryType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_ExportTypeContext
 * Method:    nativeGetGlobalType
 * Signature: (Lorg/wasmedge/ASTModuleContext;)Lorg/wasmedge/GlobalTypeContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ExportTypeContext_nativeGetGlobalType
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
