/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_LoaderContext */

#ifndef _Included_org_wasmedge_LoaderContext
#define _Included_org_wasmedge_LoaderContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_LoaderContext
 * Method:    parseFromFile
 * Signature: (Ljava/lang/String;)Lorg/wasmedge/ASTModuleContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_LoaderContext_parseFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_LoaderContext
 * Method:    parseFromBuffer
 * Signature: ([BI)Lorg/wasmedge/ASTModuleContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_LoaderContext_parseFromBuffer
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_wasmedge_LoaderContext
 * Method:    nativeInit
 * Signature: (Lorg/wasmedge/ConfigureContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_LoaderContext_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_LoaderContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_LoaderContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
