/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_ImportTypeContext */

#ifndef _Included_org_wasmedge_ImportTypeContext
#define _Included_org_wasmedge_ImportTypeContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_ImportTypeContext
 * Method:    getModuleName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wasmedge_ImportTypeContext_getModuleName
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ImportTypeContext
 * Method:    getExternalName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wasmedge_ImportTypeContext_getExternalName
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ImportTypeContext
 * Method:    getExternalType
 * Signature: ()Lorg/wasmedge/enums/ExternalType;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ImportTypeContext_getExternalType
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ImportTypeContext
 * Method:    nativeGetFunctionType
 * Signature: (Lorg/wasmedge/ASTModuleContext;)Lorg/wasmedge/FunctionTypeContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ImportTypeContext_nativeGetFunctionType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_ImportTypeContext
 * Method:    nativeGetTableType
 * Signature: (Lorg/wasmedge/ASTModuleContext;)Lorg/wasmedge/TableTypeContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ImportTypeContext_nativeGetTableType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_ImportTypeContext
 * Method:    nativeGetMemoryType
 * Signature: (Lorg/wasmedge/ASTModuleContext;)Lorg/wasmedge/MemoryTypeContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ImportTypeContext_nativeGetMemoryType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_ImportTypeContext
 * Method:    nativeGetGlobalType
 * Signature: (Lorg/wasmedge/ASTModuleContext;)Lorg/wasmedge/GlobalTypeContext;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ImportTypeContext_nativeGetGlobalType
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
