/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_CompilerContext */

#ifndef _Included_org_wasmedge_CompilerContext
#define _Included_org_wasmedge_CompilerContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_CompilerContext
 * Method:    nativeInit
 * Signature: (Lorg/wasmedge/ConfigureContext;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_CompilerContext_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_CompilerContext
 * Method:    compile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_CompilerContext_compile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_wasmedge_CompilerContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_CompilerContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
