/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_WasmEdgeExternRef */

#ifndef _Included_org_wasmedge_WasmEdgeExternRef
#define _Included_org_wasmedge_WasmEdgeExternRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_WasmEdgeExternRef
 * Method:    nativeInit
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_WasmEdgeExternRef_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeExternRef
 * Method:    getExternRefVal
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_WasmEdgeExternRef_getExternRefVal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
