/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_FunctionTypeContext */

#ifndef _Included_org_wasmedge_FunctionTypeContext
#define _Included_org_wasmedge_FunctionTypeContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_FunctionTypeContext
 * Method:    nativeInit
 * Signature: (Ljava/util/List;ILjava/util/List;I)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_FunctionTypeContext_nativeInit
  (JNIEnv *, jobject, jintArray, jintArray );

/*
 * Class:     org_wasmedge_FunctionTypeContext
 * Method:    getParameters
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jintArray JNICALL Java_org_wasmedge_FunctionTypeContext_nativeGetParameters
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_FunctionTypeContext
 * Method:    getReturns
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jintArray JNICALL Java_org_wasmedge_FunctionTypeContext_nativeGetReturns
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_FunctionTypeContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_FunctionTypeContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
