/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_Async */

#ifndef _Included_org_wasmedge_Async
#define _Included_org_wasmedge_Async
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_Async
 * Method:    nativeInit
 * Signature: ([Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_Async_nativeInit
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_wasmedge_Async
 * Method:    valid
 * Signature: ()Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_Async_valid
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_Async
 * Method:    get
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_Async_get
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_Async
 * Method:    asyncWait
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_Async_asyncWait
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_Async
 * Method:    waitFor
 * Signature: (Ljava/lang/Object;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_Async_waitFor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_Async
 * Method:    waitUntil
 * Signature: (Ljava/lang/Object;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_Async_waitUntil
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wasmedge_Async
 * Method:    swap
 * Signature: (Lorg/wasmedge/Async;Lorg/wasmedge/Async;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_Async_swap
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_wasmedge_Async
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_Async_cancel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
