/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_WasmEdgeExternRef */

#ifndef _Included_org_wasmedge_WasmEdgeExternRef
#define _Included_org_wasmedge_WasmEdgeExternRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_WasmEdgeExternRef
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_WasmEdgeExternRef_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wasmedge_WasmEdgeExternRef
 * Method:    nativeGetKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wasmedge_WasmEdgeExternRef_nativeGetKey
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_WasmEdgeExternRef
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_WasmEdgeExternRef_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
