/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_ASTModuleContext */

#ifndef _Included_org_wasmedge_ASTModuleContext
#define _Included_org_wasmedge_ASTModuleContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_ASTModuleContext
 * Method:    listImports
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ASTModuleContext_listImports
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ASTModuleContext
 * Method:    listExports
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_ASTModuleContext_listExports
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_ASTModuleContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_ASTModuleContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
