/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmedge_MemoryTypeContext */

#ifndef _Included_org_wasmedge_MemoryTypeContext
#define _Included_org_wasmedge_MemoryTypeContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmedge_MemoryTypeContext
 * Method:    getLimit
 * Signature: ()Lorg/wasmedge/WasmEdgeLimit;
 */
JNIEXPORT jobject JNICALL Java_org_wasmedge_MemoryTypeContext_getLimit
  (JNIEnv *, jobject);

/*
 * Class:     org_wasmedge_MemoryTypeContext
 * Method:    nativeInit
 * Signature: (ZJJ)V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_MemoryTypeContext_nativeInit
  (JNIEnv *, jobject, jboolean, jlong, jlong);

/*
 * Class:     org_wasmedge_MemoryTypeContext
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wasmedge_MemoryTypeContext_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
