// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2019-2026 Second State INC

//===-- wasmedge/test/meminstance/MemInstanceTest.cpp ---------------------===//
//
// Part of the WasmEdge Project.
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Tests for MemoryInstance: page limits and memory.copy overlap handling.
///
//===----------------------------------------------------------------------===//

#include "common/configure.h"
#include "common/spdlog.h"
#include "common/types.h"
#include "runtime/instance/memory.h"
#include "vm/vm.h"

#include <array>
#include <cstdint>
#include <gtest/gtest.h>
#include <memory>
#include <vector>

namespace {

using namespace WasmEdge;

// ---------------------------------------------------------------------------
// Memory page limit tests (formerly MemLimitTest).
// ---------------------------------------------------------------------------

TEST(MemInstanceTest, Limit__Pages) {
  using MemInst = WasmEdge::Runtime::Instance::MemoryInstance;
  WasmEdge::Configure Conf;
  Conf.getRuntimeConfigure().setMaxMemoryPage(256);

  MemInst Inst1(WasmEdge::AST::MemoryType(257),
                Conf.getRuntimeConfigure().getMaxMemoryPage());
  ASSERT_FALSE(Inst1.getDataPtr() == nullptr);
  EXPECT_EQ(Inst1.getPageSize(), 256U);

  MemInst Inst2(WasmEdge::AST::MemoryType(257));
  ASSERT_FALSE(Inst2.getDataPtr() == nullptr);

  MemInst Inst3(WasmEdge::AST::MemoryType(1),
                Conf.getRuntimeConfigure().getMaxMemoryPage());
  ASSERT_FALSE(Inst3.getDataPtr() == nullptr);
  ASSERT_FALSE(Inst3.growPage(256));
  ASSERT_TRUE(Inst3.growPage(255));

  MemInst Inst4(WasmEdge::AST::MemoryType(1));
  ASSERT_FALSE(Inst4.getDataPtr() == nullptr);
  ASSERT_TRUE(Inst4.growPage(256));

  MemInst Inst5(WasmEdge::AST::MemoryType(1, 128),
                Conf.getRuntimeConfigure().getMaxMemoryPage());
  ASSERT_FALSE(Inst5.getDataPtr() == nullptr);
  ASSERT_FALSE(Inst5.growPage(128));
  ASSERT_TRUE(Inst5.growPage(127));

  MemInst Inst6(WasmEdge::AST::MemoryType(1),
                Conf.getRuntimeConfigure().getMaxMemoryPage());
  ASSERT_FALSE(Inst6.growPage(0xFFFFFFFF));
}

// ---------------------------------------------------------------------------
// memory.copy overlap regression tests.
//
// The Wasm spec requires memory.copy to behave like memmove (handle
// overlapping source and destination correctly). Before the fix, the executor
// used std::copy (forward-only), which corrupted data when dst > src with
// overlap.
// ---------------------------------------------------------------------------

// Wasm module with:
//   (memory (export "mem") 1)
//   (func (export "copy") (param $dst i32) (param $src i32) (param $len i32)
//     local.get $dst
//     local.get $src
//     local.get $len
//     memory.copy)
//   (func (export "load8") (param $addr i32) (result i32)
//     local.get $addr
//     i32.load8_u)
//   (func (export "store8") (param $addr i32) (param $val i32)
//     local.get $addr
//     local.get $val
//     i32.store8)
//
// Generated by manual binary encoding.
static const std::array<WasmEdge::Byte, 105> OverlapTestWasm{
    0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x11, 0x03, 0x60,
    0x03, 0x7f, 0x7f, 0x7f, 0x00, 0x60, 0x01, 0x7f, 0x01, 0x7f, 0x60, 0x02,
    0x7f, 0x7f, 0x00, 0x03, 0x04, 0x03, 0x00, 0x01, 0x02, 0x05, 0x03, 0x01,
    0x00, 0x01, 0x07, 0x1f, 0x04, 0x04, 0x63, 0x6f, 0x70, 0x79, 0x00, 0x00,
    0x05, 0x6c, 0x6f, 0x61, 0x64, 0x38, 0x00, 0x01, 0x06, 0x73, 0x74, 0x6f,
    0x72, 0x65, 0x38, 0x00, 0x02, 0x03, 0x6d, 0x65, 0x6d, 0x02, 0x00, 0x0a,
    0x20, 0x03, 0x0c, 0x00, 0x20, 0x00, 0x20, 0x01, 0x20, 0x02, 0xfc, 0x0a,
    0x00, 0x00, 0x0b, 0x07, 0x00, 0x20, 0x00, 0x2d, 0x00, 0x00, 0x0b, 0x09,
    0x00, 0x20, 0x00, 0x20, 0x01, 0x3a, 0x00, 0x00, 0x0b};

// ValType helpers.
static const ValType I32Type = ValType(TypeCode::I32);

/// Helper: store a byte at the given address.
static void storeByte(VM::VM &VM, uint32_t Addr, uint32_t Val) {
  std::vector<ValVariant> Params = {Addr, Val};
  std::vector<ValType> ParamTypes = {I32Type, I32Type};
  auto Res = VM.execute("store8", Params, ParamTypes);
  ASSERT_TRUE(Res) << "store8 failed at addr=" << Addr;
}

/// Helper: load a byte from the given address.
static uint32_t loadByte(VM::VM &VM, uint32_t Addr) {
  std::vector<ValVariant> Params = {Addr};
  std::vector<ValType> ParamTypes = {I32Type};
  auto Res = VM.execute("load8", Params, ParamTypes);
  EXPECT_TRUE(Res) << "load8 failed at addr=" << Addr;
  return (*Res)[0].first.get<uint32_t>();
}

/// Helper: call memory.copy(dst, src, len).
static void memoryCopy(VM::VM &VM, uint32_t Dst, uint32_t Src, uint32_t Len) {
  std::vector<ValVariant> Params = {Dst, Src, Len};
  std::vector<ValType> ParamTypes = {I32Type, I32Type, I32Type};
  auto Res = VM.execute("copy", Params, ParamTypes);
  ASSERT_TRUE(Res) << "memory.copy failed: dst=" << Dst << " src=" << Src
                   << " len=" << Len;
}

/// Helper: read a range of bytes from memory.
static std::vector<uint8_t> readMemory(VM::VM &VM, uint32_t Start,
                                       uint32_t Len) {
  std::vector<uint8_t> Result;
  Result.reserve(Len);
  for (uint32_t I = 0; I < Len; ++I) {
    Result.push_back(static_cast<uint8_t>(loadByte(VM, Start + I)));
  }
  return Result;
}

/// Test fixture that creates a fresh VM with the test module for each test.
class MemCopyOverlapTest : public ::testing::Test {
protected:
  void SetUp() override {
    WasmEdge::Configure Conf;
    VMPtr = std::make_unique<VM::VM>(Conf);
    ASSERT_TRUE(VMPtr->loadWasm(OverlapTestWasm));
    ASSERT_TRUE(VMPtr->validate());
    ASSERT_TRUE(VMPtr->instantiate());
  }

  VM::VM &vm() { return *VMPtr; }

private:
  std::unique_ptr<VM::VM> VMPtr;
};

// Test: Forward overlap (dst > src, regions overlap).
// This is the case that was broken before the fix:
// std::copy iterates forward, so when dst > src, earlier writes overwrite
// source bytes that haven't been read yet.
//
// Memory layout:
//   Address: 0  1  2  3  4  5  6  7  8  9
//   Before:  A  B  C  D  E  F  G  H  .  .
//   copy(dst=3, src=0, len=5)
//   Source region:  [0..4]  = A B C D E
//   Dest region:    [3..7]
//   After (correct): A  B  C  A  B  C  D  E  .  .
//   After (buggy):   A  B  C  A  B  C  A  B  .  .  (forward copy corruption)
TEST_F(MemCopyOverlapTest, ForwardOverlap) {
  // Initialize memory[0..7] = {0x41..0x48} ('A'..'H')
  for (uint32_t I = 0; I < 8; ++I) {
    storeByte(vm(), I, 0x41 + I);
  }

  // memory.copy(dst=3, src=0, len=5)
  // Overlapping forward: dst > src, and dst < src + len
  memoryCopy(vm(), 3, 0, 5);

  // Verify: bytes at [3..7] should be the ORIGINAL [0..4] = A B C D E
  std::vector<uint8_t> Expected = {0x41, 0x42, 0x43, 0x44, 0x45};
  auto Actual = readMemory(vm(), 3, 5);
  EXPECT_EQ(Actual, Expected)
      << "Forward overlapping memory.copy produced incorrect results. "
         "This indicates that std::copy was used instead of std::memmove.";

  // Also verify that the non-overlapping prefix [0..2] is unchanged.
  std::vector<uint8_t> Prefix = {0x41, 0x42, 0x43};
  auto ActualPrefix = readMemory(vm(), 0, 3);
  EXPECT_EQ(ActualPrefix, Prefix) << "Source prefix should be unchanged.";
}

// Test: Backward overlap (dst < src, regions overlap).
// This case works correctly with forward std::copy, but we verify it anyway.
//
// Memory layout:
//   Address: 0  1  2  3  4  5  6  7  8  9
//   Before:  A  B  C  D  E  F  G  H  .  .
//   copy(dst=0, src=3, len=5)
//   Source region:  [3..7]  = D E F G H
//   Dest region:    [0..4]
//   After:   D  E  F  G  H  F  G  H  .  .
TEST_F(MemCopyOverlapTest, BackwardOverlap) {
  for (uint32_t I = 0; I < 8; ++I) {
    storeByte(vm(), I, 0x41 + I);
  }

  // memory.copy(dst=0, src=3, len=5)
  memoryCopy(vm(), 0, 3, 5);

  // Verify: bytes at [0..4] should be the original [3..7] = D E F G H
  std::vector<uint8_t> Expected = {0x44, 0x45, 0x46, 0x47, 0x48};
  auto Actual = readMemory(vm(), 0, 5);
  EXPECT_EQ(Actual, Expected)
      << "Backward overlapping memory.copy produced incorrect results.";

  // Verify that the tail [5..7] is unchanged.
  std::vector<uint8_t> Tail = {0x46, 0x47, 0x48};
  auto ActualTail = readMemory(vm(), 5, 3);
  EXPECT_EQ(ActualTail, Tail) << "Trailing bytes should be unchanged.";
}

// Test: Exact overlap (dst == src). Should be a no-op effectively.
TEST_F(MemCopyOverlapTest, ExactOverlap) {
  for (uint32_t I = 0; I < 8; ++I) {
    storeByte(vm(), I, 0x41 + I);
  }

  // memory.copy(dst=2, src=2, len=4): copy to same position
  memoryCopy(vm(), 2, 2, 4);

  // Verify: all bytes unchanged
  std::vector<uint8_t> Expected = {0x41, 0x42, 0x43, 0x44,
                                   0x45, 0x46, 0x47, 0x48};
  auto Actual = readMemory(vm(), 0, 8);
  EXPECT_EQ(Actual, Expected)
      << "Self-copy (dst == src) should leave memory unchanged.";
}

// Test: Non-overlapping copy (sanity check).
TEST_F(MemCopyOverlapTest, NonOverlapping) {
  for (uint32_t I = 0; I < 5; ++I) {
    storeByte(vm(), I, 0x41 + I);
  }
  // Zero out destination region.
  for (uint32_t I = 10; I < 15; ++I) {
    storeByte(vm(), I, 0x00);
  }

  // memory.copy(dst=10, src=0, len=5): no overlap at all
  memoryCopy(vm(), 10, 0, 5);

  // Verify: bytes at [10..14] = original [0..4]
  std::vector<uint8_t> Expected = {0x41, 0x42, 0x43, 0x44, 0x45};
  auto Actual = readMemory(vm(), 10, 5);
  EXPECT_EQ(Actual, Expected) << "Non-overlapping copy should work correctly.";

  // Source should be unchanged.
  auto ActualSrc = readMemory(vm(), 0, 5);
  EXPECT_EQ(ActualSrc, Expected) << "Source region should be unchanged.";
}

// Test: Zero-length copy (edge case).
TEST_F(MemCopyOverlapTest, ZeroLength) {
  for (uint32_t I = 0; I < 5; ++I) {
    storeByte(vm(), I, 0x41 + I);
  }

  // memory.copy(dst=0, src=2, len=0): should be a no-op
  memoryCopy(vm(), 0, 2, 0);

  std::vector<uint8_t> Expected = {0x41, 0x42, 0x43, 0x44, 0x45};
  auto Actual = readMemory(vm(), 0, 5);
  EXPECT_EQ(Actual, Expected) << "Zero-length copy should be a no-op.";
}

// Test: Large overlapping copy (forward, larger region).
// Stress-test the overlap handling with a bigger region.
TEST_F(MemCopyOverlapTest, LargeForwardOverlap) {
  // Initialize 256 bytes with sequential values.
  const uint32_t Size = 256;
  for (uint32_t I = 0; I < Size; ++I) {
    storeByte(vm(), I, I & 0xFF);
  }

  // memory.copy(dst=10, src=0, len=200): forward overlap, dst > src
  memoryCopy(vm(), 10, 0, 200);

  // Verify: bytes at [10..209] should be the original [0..199]
  for (uint32_t I = 0; I < 200; ++I) {
    uint8_t Expected = I & 0xFF;
    uint8_t Actual = static_cast<uint8_t>(loadByte(vm(), 10 + I));
    EXPECT_EQ(Actual, Expected)
        << "Large forward overlap mismatch at offset " << I;
  }
}

// Test: Adjacent regions touching at boundary (no overlap).
TEST_F(MemCopyOverlapTest, AdjacentRegions) {
  // Address: 0  1  2  3  4  5  6  7  8  9
  // Before:  A  B  C  D  E  0  0  0  0  0
  for (uint32_t I = 0; I < 5; ++I) {
    storeByte(vm(), I, 0x41 + I);
  }
  for (uint32_t I = 5; I < 10; ++I) {
    storeByte(vm(), I, 0x00);
  }

  // memory.copy(dst=5, src=0, len=5): adjacent, not overlapping
  memoryCopy(vm(), 5, 0, 5);

  std::vector<uint8_t> Expected = {0x41, 0x42, 0x43, 0x44, 0x45,
                                   0x41, 0x42, 0x43, 0x44, 0x45};
  auto Actual = readMemory(vm(), 0, 10);
  EXPECT_EQ(Actual, Expected) << "Adjacent copy should duplicate the region.";
}

// Test: Single byte overlap (minimal overlap case).
TEST_F(MemCopyOverlapTest, SingleByteOverlap) {
  // Address: 0  1  2  3  4
  // Before:  A  B  C  D  E
  for (uint32_t I = 0; I < 5; ++I) {
    storeByte(vm(), I, 0x41 + I);
  }

  // memory.copy(dst=4, src=0, len=5): overlap at exactly one byte (addr 4)
  memoryCopy(vm(), 4, 0, 5);

  // Verify: bytes at [4..8] should be original [0..4] = A B C D E
  std::vector<uint8_t> Expected = {0x41, 0x42, 0x43, 0x44, 0x45};
  auto Actual = readMemory(vm(), 4, 5);
  EXPECT_EQ(Actual, Expected)
      << "Single-byte overlap copy should produce correct results.";
}

} // namespace

GTEST_API_ int main(int argc, char **argv) {
  WasmEdge::Log::setErrorLoggingLevel();
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
