ARG BASE=wasmedge/wasmedge:ubuntu-build-clang
FROM ${BASE}

RUN apt update && apt install -y \
  wget \
  unzip

RUN rm -rf /var/lib/apt/lists/*

COPY install-opencvmini.sh .
RUN [ "/bin/bash", "install-opencvmini.sh" ]
