FROM ubuntu:22.04@sha256:4f838adc7181d9039ac795a7d0aba05a9bd9ecd480d294483169c5def983b64d

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y \
	&& apt install -y \
	ca-certificates \
	curl \
	gnupg-agent \
	software-properties-common

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository \
		"deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu \
		$(lsb_release -cs) \
		stable"

RUN apt update && apt install -y \
	docker-ce \
	docker-ce-cli \
	containerd.io
