ARG BASE=secondstate/ssvm:ubuntu-base
FROM ${BASE}

RUN apt update && apt install -y \
	software-properties-common \
	wget

RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -

RUN apt update && apt install -y \
	libllvm9 \
	llvm-9 \
	llvm-9-dev \
	liblld-9-dev \
	llvm-9-runtime \
	libclang-common-9-dev # for yaml-bench

RUN apt update && apt install -y \
	gcc-8 \
	g++-8

RUN rm -rf /var/lib/apt/lists/*

ENV CC=gcc-8
ENV CXX=g++-8
