ARG BASE_IMAGE=wasmedge/wasmedge:latest@sha256:50edb2edffd5bbf770b03c55dd21620b7050e2b9013d73b6e3ca0d1133ee99cf
ARG TOOLCHAIN=clang
FROM ${BASE_IMAGE} AS base

### env for clang
FROM base AS deps-clang

### env for gcc
FROM base AS deps-gcc

ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++

### final
FROM deps-${TOOLCHAIN} AS final
