FROM ubuntu:22.04

MAINTAINER hydai hydai@secondstate.io
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y \
	&& apt install -y \
	software-properties-common \
	dpkg-dev \
	wget \
	cmake \
	ninja-build \
	curl \
	git \
	libboost-all-dev \
	llvm-14-dev \
	liblld-14-dev

RUN rm -rf /var/lib/apt/lists/*
