ARG BASE_IMAGE="wasmedge/wasmedge:manylinux_2_28_x86_64"
FROM ${BASE_IMAGE} AS base

WORKDIR /root

### deps for x86_64 ###
FROM base AS deps-amd64
RUN cd && (yum check-update || true) && \
  yum install -y wget unzip zlib-devel zlib-static elfutils-libelf-devel

COPY wasi-nn/install-pytorch.sh .
ENV PYTORCH_VERSION="1.8.2"
ENV PYTORCH_INSTALL_TO="/root"
ENV Torch_DIR="/root/libtorch"
RUN [ "/bin/bash", "install-pytorch.sh"  ]

### deps for aarch64 ###
FROM base AS deps-arm64
RUN cd && (yum check-update || true) && \
  yum install -y wget unzip zlib-devel zlib-static

### deps for all ###
FROM deps-${TARGETARCH} AS final

COPY opencvmini/install-opencvmini.sh .
ENV OPENCV_VERSION="4.8.0"
RUN [ "/bin/bash", "install-opencvmini.sh" ]

COPY wasi-crypto/build-openssl.sh .
ENV OpenSSL_DIR="/root/openssl-1.1.1n/openssl"
RUN [ "/bin/bash", "build-openssl.sh" ]

COPY ffmpeg/install-ffmpeg-v6.0.sh .
RUN [ "/bin/bash", "install-ffmpeg-v6.0.sh" ]
ENV PKG_CONFIG_PATH=/root/FFmpeg-n6.0/output/lib/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
ENV LD_LIBRARY_PATH=/root/FFmpeg-n6.0/output/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

ENV OPENVINO_VERSION="2024.2.0"
ENV OPENVINO_YEAR="2024"

COPY wasi-nn/install-onnxruntime.sh .
RUN [ "/bin/bash", "install-onnxruntime.sh" ]

RUN yum clean all
