ARG BASE=secondstate/ssvm:ubuntu-base
FROM ${BASE}

RUN apt update && apt install -y \
	llvm-dev \
	liblld-10-dev

RUN apt update && apt install -y \
	clang

RUN rm -rf /var/lib/apt/lists/*

ENV CC=/usr/bin/clang
ENV CXX=/usr/bin/clang++
