# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# SPDX-FileCopyrightText: 2019-2022 Second State INC

ARG BASE=wasmedge/wasmedge:manylinux2014_x86_64
ARG BUILDPLATFORM=x86_64
FROM --platform=$BUILDPLATFORM ${BASE}

MAINTAINER hydai hydai@secondstate.io

ADD install-opencvmini.sh /root/

ENV PATH=/opt/rh/devtoolset-11/root/usr/bin${PATH:+:${PATH}}
ENV MANPATH=/opt/rh/devtoolset-11/root/usr/share/man${MANPATH:+:${MANPATH}}
ENV INFOPATH=/opt/rh/devtoolset-11/root/usr/share/info${INFOPATH:+:${INFOPATH}}
ENV PKG_CONFIG_PATH=/opt/rh/devtoolset-11/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
ENV OPENCV_VERSION=4.8.0

WORKDIR /root/

RUN yum update -y \
	&& yum install -y zlib-devel zlib-static cmake wget unzip \
	&& bash /root/install-opencvmini.sh

RUN yum clean all
