FROM ubuntu:22.04@sha256:4f838adc7181d9039ac795a7d0aba05a9bd9ecd480d294483169c5def983b64d
ARG VERSION

RUN apt-get update && apt-get install -y netbase
ADD WasmEdge-$VERSION-Linux.tar.gz /tmp/
RUN cp -rf /tmp/WasmEdge-$VERSION-Linux/bin/* /usr/local/bin && \
    cp -rf /tmp/WasmEdge-$VERSION-Linux/lib64/* /usr/local/lib && \
    cp -rf /tmp/WasmEdge-$VERSION-Linux/include/* /usr/local/include && \
    ldconfig /usr/local/lib
RUN rm -rf /tmp/WasmEdge-$VERSION-Linux

WORKDIR /app
CMD ["/usr/local/bin/wasmedge"]
