FROM ubuntu:20.04@sha256:8feb4d8ca5354def3d8fce243717141ce31e2c428701f6682bd2fafe15388214

MAINTAINER hydai hydai@secondstate.io
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y \
	&& apt install -y \
	software-properties-common \
	wget \
	cmake \
	ninja-build \
	curl \
	git \
	dpkg-dev \
	llvm-12-dev \
	liblld-12-dev \
	gcc \
	rpm \
	g++

RUN rm -rf /var/lib/apt/lists/*

ENV CC=gcc
ENV CXX=g++
