// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The WasmEdge Authors

//===-- wasmedge/test/vm/VMTest.cpp - VM characterization tests -----------===//
//
// Part of the WasmEdge Project.
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Characterization tests pinning the observable VM behavior: the stage
/// machine, module registration, plugin mock fallback, and cleanup-reuse.
///
//===----------------------------------------------------------------------===//

#include "vm/vm.h"

#include "common/configure.h"
#include "common/errcode.h"
#include "common/spdlog.h"
#include "common/types.h"

#include <gtest/gtest.h>

#include <array>
#include <cstdint>
#include <vector>

namespace {

using namespace WasmEdge;

// Wasm module with:
//   (func (export "f") (result i32) i32.const 7)
// Generated by manual binary encoding.
static const std::array<WasmEdge::Byte, 34> ConstFuncWasm{
    0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
    0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07, 0x05, 0x01, 0x01, 0x66,
    0x00, 0x00, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x41, 0x07, 0x0b};

/// Helper: drive the VM through load, validate, and instantiate.
void instantiateFixture(VM::VM &TestVM) {
  ASSERT_TRUE(TestVM.loadWasm(ConstFuncWasm));
  ASSERT_TRUE(TestVM.validate());
  ASSERT_TRUE(TestVM.instantiate());
}

/// Helper: execute the exported function and expect the constant result.
void expectConstResult(VM::VM &TestVM) {
  auto Res = TestVM.execute("f");
  ASSERT_TRUE(Res);
  ASSERT_EQ(Res->size(), 1U);
  EXPECT_EQ((*Res)[0].first.get<uint32_t>(), 7U);
}

TEST(VMStageTest, ValidateBeforeLoadFails) {
  Configure Conf;
  VM::VM TestVM(Conf);
  auto Res = TestVM.validate();
  ASSERT_FALSE(Res);
  EXPECT_EQ(Res.error(), ErrCode::Value::WrongVMWorkflow);
}

TEST(VMStageTest, InstantiateBeforeValidateFails) {
  Configure Conf;
  VM::VM FreshVM(Conf);
  auto FreshRes = FreshVM.instantiate();
  ASSERT_FALSE(FreshRes);
  EXPECT_EQ(FreshRes.error(), ErrCode::Value::WrongVMWorkflow);

  VM::VM LoadedVM(Conf);
  ASSERT_TRUE(LoadedVM.loadWasm(ConstFuncWasm));
  auto LoadedRes = LoadedVM.instantiate();
  ASSERT_FALSE(LoadedRes);
  EXPECT_EQ(LoadedRes.error(), ErrCode::Value::WrongVMWorkflow);
}

TEST(VMStageTest, ExecuteWithoutInstanceFails) {
  Configure Conf;
  VM::VM TestVM(Conf);
  auto Res = TestVM.execute("f");
  ASSERT_FALSE(Res);
  EXPECT_EQ(Res.error(), ErrCode::Value::WrongInstanceAddress);
}

TEST(VMStageTest, HappyPathLoadValidateInstantiateExecute) {
  Configure Conf;
  VM::VM TestVM(Conf);
  EXPECT_FALSE(TestVM.holdsModule());
  instantiateFixture(TestVM);
  EXPECT_TRUE(TestVM.holdsModule());
  expectConstResult(TestVM);

  auto FnList = TestVM.getFunctionList();
  ASSERT_EQ(FnList.size(), 1U);
  EXPECT_EQ(FnList[0].first, "f");
}

TEST(VMStageTest, RegisterWhileInstantiatedAllowsReinstantiate) {
  Configure Conf;
  VM::VM TestVM(Conf);
  instantiateFixture(TestVM);
  ASSERT_TRUE(TestVM.registerModule("ext", ConstFuncWasm));
  ASSERT_TRUE(TestVM.instantiate());
  expectConstResult(TestVM);
}

TEST(VMRegistrationTest, RegisterAndExecuteByName) {
  Configure Conf;
  VM::VM TestVM(Conf);
  ASSERT_TRUE(TestVM.registerModule("ext", ConstFuncWasm));
  auto Res = TestVM.execute("ext", "f");
  ASSERT_TRUE(Res);
  ASSERT_EQ(Res->size(), 1U);
  EXPECT_EQ((*Res)[0].first.get<uint32_t>(), 7U);
}

TEST(VMRegistrationTest, DuplicateNameFails) {
  Configure Conf;
  VM::VM TestVM(Conf);
  ASSERT_TRUE(TestVM.registerModule("dup", ConstFuncWasm));
  auto Res = TestVM.registerModule("dup", ConstFuncWasm);
  ASSERT_FALSE(Res);
  EXPECT_EQ(Res.error(), ErrCode::Value::ModuleNameConflict);
}

TEST(VMRegistrationTest, UnregisterRemovesStoreLookup) {
  Configure Conf;
  VM::VM TestVM(Conf);
  ASSERT_TRUE(TestVM.registerModule("ext", ConstFuncWasm));
  {
    auto Res = TestVM.execute("ext", "f");
    ASSERT_TRUE(Res);
  }
  ASSERT_TRUE(TestVM.unregisterModule("ext"));
  auto Res = TestVM.execute("ext", "f");
  ASSERT_FALSE(Res);
  EXPECT_EQ(Res.error(), ErrCode::Value::WrongInstanceAddress);
}

TEST(VMRegistrationTest, UnregisterUnknownNameSucceeds) {
  Configure Conf;
  VM::VM TestVM(Conf);
  EXPECT_TRUE(TestVM.unregisterModule("no-such-module"));
}

TEST(VMPluginTest, MockPluginModulesRegistered) {
  Configure Conf;
  VM::VM TestVM(Conf);
  EXPECT_NE(TestVM.getStoreManager().findModule("wasi_ephemeral_nn"), nullptr);
}

TEST(VMPluginTest, WasiImportModulePresence) {
  Configure ConfWithWasi;
  ConfWithWasi.addHostRegistration(HostRegistration::Wasi);
  VM::VM WasiVM(ConfWithWasi);
  EXPECT_NE(WasiVM.getImportModule(HostRegistration::Wasi), nullptr);

  Configure ConfPlain;
  VM::VM PlainVM(ConfPlain);
  EXPECT_EQ(PlainVM.getImportModule(HostRegistration::Wasi), nullptr);
}

TEST(VMCleanupTest, VMIsReusableAfterCleanup) {
  Configure Conf;
  VM::VM TestVM(Conf);
  instantiateFixture(TestVM);
  expectConstResult(TestVM);

  TestVM.cleanup();
  auto Res = TestVM.execute("f");
  ASSERT_FALSE(Res);
  EXPECT_EQ(Res.error(), ErrCode::Value::WrongInstanceAddress);

  instantiateFixture(TestVM);
  expectConstResult(TestVM);
}

TEST(VMCleanupTest, CleanupRestoresBuiltinHosts) {
  Configure Conf;
  Conf.addHostRegistration(HostRegistration::Wasi);
  VM::VM TestVM(Conf);
  ASSERT_NE(TestVM.getImportModule(HostRegistration::Wasi), nullptr);
  TestVM.cleanup();
  EXPECT_NE(TestVM.getImportModule(HostRegistration::Wasi), nullptr);
  EXPECT_NE(TestVM.getStoreManager().findModule("wasi_ephemeral_nn"), nullptr);
}

} // namespace

GTEST_API_ int main(int argc, char **argv) {
  WasmEdge::Log::setErrorLoggingLevel();
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
