function(wasmedge_llvm_linker_backend_for_processor Output Processor)
  string(TOLOWER "${Processor}" Processor)
  if(Processor MATCHES "^(x86_64|x86_64h|amd64)(-.*)?$")
    set(Backend X86_64)
  elseif(Processor MATCHES "^(aarch64|arm64)(-.*)?$")
    set(Backend AARCH64)
  elseif(Processor MATCHES
      "^(arm|armv7|armv7-a|armv7a|armv7l|armv8|armv8-a|armv8a|armv8l)(-.*)?$")
    set(Backend ARM)
  elseif(Processor MATCHES "^riscv64(gc)?(-.*)?$")
    set(Backend RISCV64)
  elseif(Processor MATCHES "^(s390x|systemz)(-.*)?$")
    set(Backend S390X)
  else()
    set(Backend "")
  endif()
  set(${Output} "${Backend}" PARENT_SCOPE)
endfunction()

function(wasmedge_llvm_linker_backends_for_processors Output Processors)
  set(Backends "")
  set(Unmatched "")
  foreach(Processor IN LISTS Processors)
    wasmedge_llvm_linker_backend_for_processor(Backend "${Processor}")
    if(Backend STREQUAL "")
      list(APPEND Unmatched "${Processor}")
    elseif(NOT Backend IN_LIST Backends)
      list(APPEND Backends "${Backend}")
    endif()
  endforeach()
  set(${Output} "${Backends}" PARENT_SCOPE)
  if(ARGC GREATER 2)
    set(${ARGV2} "${Unmatched}" PARENT_SCOPE)
  endif()
endfunction()

function(wasmedge_select_llvm_linker_backends Output Error)
  set(ParseArguments "")
  set(RequestedDefined FALSE)
  set(Index 2)
  while(Index LESS ARGC)
    if(DEFINED ARGV${Index} AND ARGV${Index} STREQUAL "REQUESTED")
      math(EXPR Index "${Index} + 1")
      if(Index GREATER_EQUAL ARGC)
        set(${Output} "" PARENT_SCOPE)
        set(${Error}
          "WASMEDGE_LLVM_LINKER_RELOCATION_BACKENDS value is missing"
          PARENT_SCOPE)
        return()
      endif()
      set(Argument_REQUESTED "${ARGV${Index}}")
      set(RequestedDefined TRUE)
    else()
      list(APPEND ParseArguments "${ARGV${Index}}")
    endif()
    math(EXPR Index "${Index} + 1")
  endwhile()
  cmake_parse_arguments(Argument
    "BUILD_TESTS;USE_LLVM" "PROCESSOR" "ARCHITECTURES" ${ParseArguments})
  if(NOT RequestedDefined)
    set(Argument_REQUESTED AUTO)
  endif()

  set(Unmatched "")
  if(Argument_BUILD_TESTS)
    set(Default X86_64 AARCH64 ARM RISCV64 S390X)
  elseif(Argument_ARCHITECTURES)
    wasmedge_llvm_linker_backends_for_processors(
      Default "${Argument_ARCHITECTURES}" Unmatched)
  else()
    wasmedge_llvm_linker_backend_for_processor(
      Default "${Argument_PROCESSOR}")
  endif()

  if(Argument_REQUESTED STREQUAL "AUTO")
    set(Selected ${Default})
  else()
    set(Selected ${Argument_REQUESTED})
  endif()

  set(Allowed X86_64 AARCH64 ARM RISCV64 S390X)
  set(Normalized "")
  foreach(Backend IN LISTS Selected)
    string(TOUPPER "${Backend}" BackendNormalized)
    if(NOT BackendNormalized IN_LIST Allowed)
      set(${Output} "" PARENT_SCOPE)
      set(${Error}
        "Unknown WASMEDGE_LLVM_LINKER_RELOCATION_BACKENDS value: ${Backend}"
        PARENT_SCOPE)
      return()
    endif()
    if(BackendNormalized IN_LIST Normalized)
      set(${Output} "" PARENT_SCOPE)
      set(${Error}
        "Duplicate WASMEDGE_LLVM_LINKER_RELOCATION_BACKENDS value: ${BackendNormalized}"
        PARENT_SCOPE)
      return()
    endif()
    list(APPEND Normalized "${BackendNormalized}")
  endforeach()

  if(Argument_USE_LLVM AND Argument_REQUESTED STREQUAL "AUTO" AND
     (NOT Normalized OR Unmatched))
    set(SelectionError
      "AUTO could not select an LLVM linker relocation backend: CMAKE_SYSTEM_PROCESSOR='${Argument_PROCESSOR}', CMAKE_OSX_ARCHITECTURES='${Argument_ARCHITECTURES}', unmatched architectures='${Unmatched}'. Set WASMEDGE_LLVM_LINKER_RELOCATION_BACKENDS explicitly.")
  else()
    set(SelectionError "")
  endif()
  set(${Output} "${Normalized}" PARENT_SCOPE)
  set(${Error} "${SelectionError}" PARENT_SCOPE)
endfunction()

function(wasmedge_cmake_cache_argument Output Name Type Value)
  string(REPLACE ";" "\\;" Value "${Value}")
  set(${Output} "-D${Name}:${Type}=${Value}" PARENT_SCOPE)
endfunction()

function(wasmedge_read_cmake_cache_value Output CacheFile Name Type)
  file(READ "${CacheFile}" Cache)
  string(REGEX MATCH "(^|\n)${Name}:${Type}=([^\n\r]*)" Match "${Cache}")
  if(NOT Match)
    message(FATAL_ERROR "${Name}:${Type} is missing from ${CacheFile}")
  endif()
  set(Value "${CMAKE_MATCH_2}")
  string(REPLACE "\\;" ";" Value "${Value}")
  set(${Output} "${Value}" PARENT_SCOPE)
endfunction()
