function(wasmedge_llvm_linker_backend_for_processor Output Processor)
  string(TOLOWER "${Processor}" Processor)
  if(Processor MATCHES "^(x86_64|x86_64h|amd64)(-.*)?$")
    set(Backend X86_64)
  elseif(Processor MATCHES "^(aarch64|arm64)(-.*)?$")
    set(Backend AARCH64)
  elseif(Processor MATCHES
      "^(arm|armv7|armv7-a|armv7a|armv7l|armv8|armv8-a|armv8a|armv8l)(-.*)?$")
    set(Backend ARM)
  elseif(Processor MATCHES "^riscv64(gc)?(-.*)?$")
    set(Backend RISCV64)
  elseif(Processor MATCHES "^(s390x|systemz)(-.*)?$")
    set(Backend S390X)
  else()
    set(Backend "")
  endif()
  set(${Output} "${Backend}" PARENT_SCOPE)
endfunction()

function(wasmedge_llvm_linker_backends_for_processors Output Processors)
  set(Backends "")
  set(Unmatched "")
  foreach(Processor IN LISTS Processors)
    wasmedge_llvm_linker_backend_for_processor(Backend "${Processor}")
    if(Backend STREQUAL "")
      list(APPEND Unmatched "${Processor}")
    elseif(NOT Backend IN_LIST Backends)
      list(APPEND Backends "${Backend}")
    endif()
  endforeach()
  set(${Output} "${Backends}" PARENT_SCOPE)
  if(ARGC GREATER 2)
    set(${ARGV2} "${Unmatched}" PARENT_SCOPE)
  endif()
endfunction()

function(wasmedge_cmake_cache_argument Output Name Type Value)
  string(REPLACE ";" "\\;" Value "${Value}")
  set(${Output} "-D${Name}:${Type}=${Value}" PARENT_SCOPE)
endfunction()

function(wasmedge_read_cmake_cache_value Output CacheFile Name Type)
  file(READ "${CacheFile}" Cache)
  string(REGEX MATCH "(^|\n)${Name}:${Type}=([^\n\r]*)" Match "${Cache}")
  if(NOT Match)
    message(FATAL_ERROR "${Name}:${Type} is missing from ${CacheFile}")
  endif()
  set(Value "${CMAKE_MATCH_2}")
  string(REPLACE "\\;" ";" Value "${Value}")
  set(${Output} "${Value}" PARENT_SCOPE)
endfunction()
