function(wasmedge_select_static_zstd_archive Output)
  set(Archive)
  set(FallbackArchive)
  if(TARGET zstd::libzstd_static)
    set(Archive zstd::libzstd_static)
  elseif(zstd_STATIC_LIBRARY AND EXISTS "${zstd_STATIC_LIBRARY}")
    set(Archive "${zstd_STATIC_LIBRARY}")
  endif()
  if(NOT Archive AND zstd_LIBRARY)
    get_filename_component(ZstdPath "${zstd_LIBRARY}" DIRECTORY)
    if(MSVC OR "${CMAKE_CXX_SIMULATE_ID}" STREQUAL "MSVC")
      set(FallbackArchive
        "${ZstdPath}/zstd_static${CMAKE_STATIC_LIBRARY_SUFFIX}")
    else()
      set(FallbackArchive
        "${ZstdPath}/${CMAKE_STATIC_LIBRARY_PREFIX}zstd${CMAKE_STATIC_LIBRARY_SUFFIX}")
    endif()
    if(EXISTS "${FallbackArchive}")
      set(Archive "${FallbackArchive}")
    endif()
  endif()
  if(NOT Archive)
    message(FATAL_ERROR
      "LLVM requires a static zstd target or library, but none exists. Checked zstd::libzstd_static, zstd_STATIC_LIBRARY='${zstd_STATIC_LIBRARY}', and '${FallbackArchive}'")
  endif()
  set(${Output} "${Archive}" PARENT_SCOPE)
endfunction()
