# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright The WasmEdge Authors

include(${CMAKE_CURRENT_LIST_DIR}/TensorflowDeps.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wasi_nn/bitnet.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wasi_nn/chattts.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wasi_nn/ggml.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wasi_nn/mlx.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wasi_nn/openvino.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wasi_nn/openvino_genai.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wasi_nn/piper.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wasi_nn/pytorch.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wasi_nn/whisper.cmake)

# Function for setting up a WASI-NN target.
function(wasmedge_setup_wasinn_target target)
  cmake_parse_arguments(PARSE_ARGV 1 WASMEDGE_WASINNDEPS_${target} "PLUGINLIB" "" "")
  # The `PLUGINLIB` keyword marks the target that is the plugin library.
  # Some dependencies must be fully linked because invocation happens in the plugin header.
  # In other cases, includes are needed only if the target is not the plugin library, such as the tests.

  foreach(BACKEND ${WASMEDGE_PLUGIN_WASI_NN_BACKEND})
    string(TOLOWER ${BACKEND} BACKEND)
    if(BACKEND STREQUAL "openvino")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build OpenVINO backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_OPENVINO)
      wasmedge_setup_openvino_target(${target})
    elseif(BACKEND STREQUAL "openvinogenai")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build OpenVINO GenAI backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_OPENVINOGENAI)
      wasmedge_setup_openvino_genai_target(${target})
    elseif(BACKEND STREQUAL "pytorch")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build PyTorch backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_TORCH)
      wasmedge_setup_pytorch_target(${target})
    elseif(BACKEND STREQUAL "tensorflowlite")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build Tensorflow-lite backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_TFLITE)
      wasmedge_setup_tflite_target(${target})
    elseif(BACKEND STREQUAL "ggml")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build ggml backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_GGML)
      wasmedge_setup_llama_target(${target})
    elseif(BACKEND STREQUAL "neuralspeed")
      message(FATAL_ERROR "WASI-NN: Neural Speed backend is removed due to the upstream end-of-life. Reference: https://github.com/intel/neural-speed")
    elseif(BACKEND STREQUAL "piper")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build piper backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_PIPER)
      wasmedge_setup_piper_target(${target})
    elseif(BACKEND STREQUAL "whisper")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build whisper.cpp backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_WHISPER)
      wasmedge_setup_whisper_target(${target})
    elseif(BACKEND STREQUAL "chattts")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build chatTTS backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_CHATTTS)
      wasmedge_setup_chattts_target(${target})
    elseif(BACKEND STREQUAL "mlx")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build MLX backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_MLX)
      wasmedge_setup_mlx_target(${target})
    elseif(BACKEND STREQUAL "bitnet")
      if(WASMEDGE_WASINNDEPS_${target}_PLUGINLIB)
        message(STATUS "WASI-NN: Build bitnet.cpp backend for WASI-NN")
      endif()
      target_compile_definitions(${target} PUBLIC WASMEDGE_PLUGIN_WASI_NN_BACKEND_BITNET)
      wasmedge_setup_bitnet_target(${target})
    else()
      # Add messages for other backends here.
      message(FATAL_ERROR "WASI-NN: backend ${BACKEND} not found or unimplemented.")
    endif()
  endforeach()
endfunction()
