include(GNUInstallDirs)

add_library(WasmEdge::WasmEdge STATIC IMPORTED)
target_include_directories(WasmEdge::WasmEdge INTERFACE "${WASMEDGE_ROOT}/include")
target_link_libraries(WasmEdge::WasmEdge INTERFACE curses)
if(APPLE)
  target_link_libraries(WasmEdge::WasmEdge INTERFACE xar)
endif()
set(WASMEDGE_LIB "${WASMEDGE_ROOT}/${CMAKE_INSTALL_LIBDIR}/libwasmedge.a")
set(WASMEDGE_LIB_DEBUG "${WASMEDGE_ROOT}/${CMAKE_INSTALL_LIBDIR}/libwasmedged.a")
if(NOT EXISTS "${WASMEDGE_LIB}")
  set(WASMEDGE_LIB "${WASMEDGE_LIB_DEBUG}")
endif()
set_property(TARGET WasmEdge::WasmEdge PROPERTY IMPORTED_LOCATION "${WASMEDGE_LIB}")
if(EXISTS "${WASMEDGE_LIB_DEBUG}")
  set_property(TARGET WasmEdge::WasmEdge PROPERTY IMPORTED_LOCATION_DEBUG "${WASMEDGE_LIB_DEBUG}")
endif()
