[book]
title = "WasmEdge Runtime"
description = ""
author = ["Second State", "Michael Yuan", "Vivian Hu", "Miley Fu", "YiYing He"]
language = "en"

[output.html]
git-repository-url = "https://github.com/WasmEdge/WasmEdge"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/WasmEdge/WasmEdge/tree/master/docs/book/en/{path}"
site-url = "/book/en/"
cname = "wasmedge.org"

[output.html.playground]
editable = false
copy-js = true
line-numbers = false

[output.html.fold]
enable = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[output.html.redirect]
"/intro.html" = "/book/en/index.html"
"/start/install.html" = "/book/en/quick_start/install.html"
"/start/docker.html" = "/book/en/quick_start/use_docker.html"
"/start/cli.html" = "/book/en/quick_start/run_cli.html"
"/start/universal.html" = "/book/en/quick_start/run_in_aot_mode.html"
"/intro/features.html" = "/book/en/features.html"
"/intro/standard.html" = "/book/en/features/proposals.html"
"/intro/proprietary.html" = "/book/en/features/proprietary_extend.html"
"/intro/integrations.html" = "/book/en/features/integrations.html"
"/intro/faq.html" = "/book/en/features/comparison.html"
"/intro/use.html" = "/book/en/use_cases.html"
"/intro/use/jamstack.html" = "/book/en/use_cases/server_side_render.html"
"/intro/use/microservice.html" = "/book/en/use_cases/microservice.html"
"/intro/use/serverless.html" = "/book/en/use_cases/serverless_faas.html"
"/intro/use/saas.html" = "/book/en/use_cases/serverless_saas.html"
"/intro/use/device.html" = "/book/en/use_cases/smart_device.html"
"/intro/use/js.html" = "/book/en/use_cases/js_or_dsl_runtime.html"
"/kubernetes.html" = "/book/en/use_cases/kubernetes.html"
"/kubernetes/quickstart.html" = "/book/en/use_cases/kubernetes/quickstart.html"
"/kubernetes/demo.html" = "/book/en/use_cases/kubernetes/demo.html"
"/kubernetes/demo/wasi.html" = "/book/en/use_cases/kubernetes/demo/wasi.html"
"/kubernetes/demo/server.html" = "/book/en/use_cases/kubernetes/demo/server.html"
"/kubernetes/container.html" = "/book/en/use_cases/kubernetes/container.html"
"/kubernetes/container/crun.html" = "/book/en/use_cases/kubernetes/container/crun.html"
"/kubernetes/container/runc.html" = "/book/en/use_cases/kubernetes/container/runc.html"
"/kubernetes/container/youki.html" = "/book/en/use_cases/kubernetes/container/youki.html"
"/kubernetes/cri.html" = "/book/en/use_cases/kubernetes/cri.html"
"/kubernetes/cri/crio.html" = "/book/en/use_cases/kubernetes/cri/crio.html"
"/kubernetes/cri/containerd.html" = "/book/en/use_cases/kubernetes/cri/containerd.html"
"/kubernetes/kubernetes.html" = "/book/en/use_cases/kubernetes/kubernetes.html"
"/kubernetes/kubernetes/kubernetes-crio.html" = "/book/en/use_cases/kubernetes/kubernetes/kubernetes-crio.html"
"/kubernetes/kubernetes/kubernetes-containerd.html" = "/book/en/use_cases/kubernetes/kubernetes/kubernetes-containerd.html"
"/kubernetes/kubernetes/kind.html" = "/book/en/use_cases/kubernetes/kubernetes/kind.html"
"/kubernetes/kubernetes/kubeedge.html" = "/book/en/use_cases/kubernetes/kubernetes/kubeedge.html"
"/kubernetes/kubernetes/superedge.html" = "/book/en/use_cases/kubernetes/kubernetes/superedge.html"
"/kubernetes/kubernetes/openyurt.html" = "/book/en/use_cases/kubernetes/kubernetes/openyurt.html"
"/kubernetes/docker.html" = "/book/en/use_cases/kubernetes/docker.html"
"/kubernetes/docker/lxc.html" = "/book/en/use_cases/kubernetes/docker/lxc.html"
"/kubernetes/docker/containerd.html" = "/book/en/use_cases/kubernetes/docker/containerd.html"
"/frameworks.html" = "/book/en/use_cases/frameworks.html"
"/frameworks/mesh.html" = "/book/en/use_cases/frameworks/mesh.html"
"/frameworks/mesh/dapr.html" = "/book/en/use_cases/frameworks/mesh/dapr.html"
"/frameworks/mesh/mosn.html" = "/book/en/use_cases/frameworks/mesh/mosn.html"
"/frameworks/mesh/wasm-nginx-module.html" = "/book/en/use_cases/frameworks/mesh/wasm-nginx-module.html"
"/frameworks/mesh/eventmesh.html" = "/book/en/use_cases/frameworks/mesh/eventmesh.html"
"/frameworks/app.html" = "/book/en/use_cases/frameworks/app.html"
"/frameworks/app/yomo.html" = "/book/en/use_cases/frameworks/app/yomo.html"
"/frameworks/app/reactr.html" = "/book/en/use_cases/frameworks/app/reactr.html"
"/frameworks/serverless.html" = "/book/en/use_cases/frameworks/serverless.html"
"/frameworks/serverless/vercel.html" = "/book/en/use_cases/frameworks/serverless/vercel.html"
"/frameworks/serverless/netlify.html" = "/book/en/use_cases/frameworks/serverless/netlify.html"
"/frameworks/serverless/aws.html" = "/book/en/use_cases/frameworks/serverless/aws.html"
"/frameworks/serverless/tencent.html" = "/book/en/use_cases/frameworks/serverless/tencent.html"
"/frameworks/serverless/secondstate.html" = "/book/en/use_cases/frameworks/serverless/secondstate.html"
"/dev.html" = "/book/en/write_wasm.html"
"/dev/rust.html" = "/book/en/write_wasm/rust.html"
"/dev/rust/bindgen.html" = "/book/en/write_wasm/rust/bindgen.html"
"/dev/rust/command.html" = "/book/en/write_wasm/rust/command.html"
"/dev/rust/networking.html" = "/book/en/write_wasm/rust/networking.html"
"/dev/rust/networking-https.html" = "/book/en/write_wasm/rust/networking-https.html"
"/dev/rust/networking-nonblocking.html" = "/book/en/write_wasm/rust/networking-nonblocking.html"
"/dev/rust/ssr.html" = "/book/en/write_wasm/rust/ssr.html"
"/dev/rust/tensorflow.html" = "/book/en/write_wasm/rust/tensorflow.html"
"/dev/rust/wasi.html" = "/book/en/write_wasm/rust/wasi.html"
"/dev/rust/wasicrypto.html" = "/book/en/write_wasm/rust/wasicrypto.html"
"/dev/rust/wasinn.html" = "/book/en/write_wasm/rust/wasinn.html"
"/dev/js.html" = "/book/en/write_wasm/js.html"
"/dev/js/es6.html" = "/book/en/write_wasm/js/es6.html"
"/dev/js/modules.html" = "/book/en/write_wasm/js/modules.html"
"/dev/js/networking.html" = "/book/en/write_wasm/js/networking.html"
"/dev/js/nodejs.html" = "/book/en/write_wasm/js/nodejs.html"
"/dev/js/npm.html" = "/book/en/write_wasm/js/npm.html"
"/dev/js/quickstart.html" = "/book/en/write_wasm/js/quickstart.html"
"/dev/js/rust.html" = "/book/en/write_wasm/js/rust.html"
"/dev/js/ssr.html" = "/book/en/write_wasm/js/ssr.html"
"/dev/js/tensorflow.html" = "/book/en/write_wasm/js/tensorflow.html"
"/dev/as.html" = "/book/en/write_wasm/as.html"
"/dev/grain.html" = "/book/en/write_wasm/grain.html"
"/dev/go.html" = "/book/en/write_wasm/go.html"
"/dev/kotlin.html" = "/book/en/write_wasm/kotlin.html"
"/dev/python.html" = "/book/en/write_wasm/python.html"
"/dev/swift.html" = "/book/en/write_wasm/swift.html"
"/embed.html" = "/book/en/sdk.html"
"/embed/c.html" = "/book/en/sdk/c.html"
"/embed/c/ref.html" = "/book/en/sdk/c/ref.html"
"/embed/c/0.10.1/ref.html" = "/book/en/sdk/c/0.10.1/ref.html"
"/embed/c/0.10.1/upgrade_to_0.11.0.html" = "/book/en/sdk/c/0.10.1/upgrade_to_0.11.0.html"
"/embed/c/0.9.1/ref.html" = "/book/en/sdk/c/0.9.1/ref.html"
"/embed/c/0.9.1/upgrade_to_0.10.0.html" = "/book/en/sdk/c/0.9.1/upgrade_to_0.10.0.html"
"/embed/go.html" = "/book/en/sdk/go.html"
"/embed/go/ref.html" = "/book/en/sdk/go/ref.html"
"/embed/go/app.html" = "/book/en/sdk/go/app.html"
"/embed/go/bindgen.html" = "/book/en/sdk/go/bindgen.html"
"/embed/go/function.html" = "/book/en/sdk/go/function.html"
"/embed/go/memory.html" = "/book/en/sdk/go/memory.html"
"/embed/go/tensorflow.html" = "/book/en/sdk/go/tensorflow.html"
"/embed/go/0.9.1/ref.html" = "/book/en/sdk/go/0.9.1/ref.html"
"/embed/go/0.9.1/upgrade_to_0.10.0.html" = "/book/en/sdk/go/0.9.1/upgrade_to_0.10.0.html"
"/embed/node.html" = "/book/en/sdk/node.html"
"/embed/python.html" = "/book/en/sdk/python.html"
"/embed/rust.html" = "/book/en/sdk/rust.html"
"/embed/rust/concurrent_fib.html" = "/book/en/sdk/rust/concurrent_fib.html"
"/embed/rust/how_to_use_module_instance.html" = "/book/en/sdk/rust/how_to_use_module_instance.html"
"/embed/rust/memory_manipulation.html" = "/book/en/sdk/rust/memory_manipulation.html"
"/embed/rust/say_hello.html" = "/book/en/sdk/rust/say_hello.html"
"/embed/rust/sys_run_host_func.html" = "/book/en/sdk/rust/sys_run_host_func.html"
"/embed/rust/table_and_funcref.html" = "/book/en/sdk/rust/table_and_funcref.html"
"/extend/plugin.html" = "/book/en/plugin.html"
"/extend/plugin/loadable.html" = "/book/en/plugin.html"
"/extend/plugin/externref.html" = "/book/en/sdk/c/externref.html"
"/extend/plugin/hostfunction.html" = "/book/en/sdk/c/hostfunction.html"
"/extend.html" = "/book/en/contribute.html"
"/extend/contribute.html" = "/book/en/contribute.html"
"/os.html" = "/book/en/features/platforms.html"
"/os/linux.html" = "/book/en/contribute/build_from_src/linux.html"
"/os/windows.html" = "/book/en/contribute/build_from_src/windows.html"
"/os/mac.html" = "/book/en/contribute/build_from_src/macos.html"
"/os/android.html" = "/book/en/contribute/build_from_src/android.html"
"/os/android/cli.html" = "/book/en/contribute/build_from_src/android/cli.html"
"/os/android/ndk.html" = "/book/en/contribute/build_from_src/android/ndk.html"
"/os/android/apk.html" = "/book/en/contribute/build_from_src/android/apk.html"
"/os/sel4.html" = "/book/en/contribute/build_from_src/sel4.html"
"/os/openharmony.html" = "/book/en/contribute/build_from_src/openharmony.html"
"/os/raspberrypi.html" = "/book/en/contribute/build_from_src/raspberrypi.html"
"/extend/build.html" = "/book/en/contribute/build_from_src.html"
"/extend/build_on_mac.html" = "/book/en/contribute/build_from_src/macos.html"
"/extend/build_on_windows.html" = "/book/en/contribute/build_from_src/windows.html"
"/extend/build_for_android.html" = "/book/en/contribute/build_from_src/android.html"

[preprocessor.variables.variables]
wasmedge_version = "0.11.2"
