name: Build WasmEdge on Nix

on:
  push:
    branches:
      - master
    paths:
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build_for_nix.yml"
      - "include/**"
      - "lib/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"
  pull_request:
    branches:
      - master
      - "proposal/**"
    paths:
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build_for_nix.yml"
      - "include/**"
      - "lib/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"

permissions:
  contents: read

jobs:
  build_nix:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - run: nix build
    - run: nix flake check
