name: Build WASI-NN ggml (HIP)

on:
  workflow_dispatch:

jobs:
  build-hip:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup deps
        run: |
          sudo apt update
          # Add ROCm repo & install minimal packages (example)
          # NOTE: check AMD docs for exact packages for your ROCm version
          sudo apt install -y build-essential cmake ninja-build pkg-config
          # Install ROCm (this step often needs special apt keys & kernel support)
          # For CI, consider using a container that already includes ROCm
          wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
          echo "deb [arch=amd64] https://repo.radeon.com/rocm/apt/5.7/ ubuntu main" | sudo tee /etc/apt/sources.list.d/rocm.list
          sudo apt update
          sudo apt install -y hip-dev rocm-cmake
      - name: Setup HIP env
        run: scripts/setup_hip_env.sh
      - name: Build with HIP
        run: scripts/build_wasi_nn_ggml_hip.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasmedge-wasi-nn-ggml-hip
          path: '**/wasmedge-wasi-nn-ggml-hip-*.tar.gz'
