name: Build WasmEdge on Nix

on:
  push:
    branches:
      - master
    paths:
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build_for_nix.yml"
      - "include/**"
      - "lib/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"
  pull_request:
    branches:
      - master
      - "proposal/**"
    paths:
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build_for_nix.yml"
      - "include/**"
      - "lib/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"

permissions:
  contents: read

jobs:
  build_nix:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - run: nix build
    - run: nix flake check
