name: Build WasmEdge on Nix

on:
  push:
    branches:
      - master
    paths:
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build_for_nix.yml"
      - "include/**"
      - "lib/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"
  pull_request:
    branches:
      - master
      - "proposal/**"
    paths:
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build_for_nix.yml"
      - "include/**"
      - "lib/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"

permissions:
  contents: read

jobs:
  build_nix:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - run: nix build
    - run: nix flake check
