name: DCO
# DCO bot is stuck. See https://github.com/dcoapp/app/issues/211
# As a workaround, we have to use DCO workflow instead.

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  dco:
    name: DCO check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python 3.x for DCO check
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Check DCO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -U dco-check
          # Don't trigger DCO bot when the PR owner is dependabot[bot]
          dco-check --verbose --exclude-pattern 'dependabot\[bot\]@users\.noreply\.github\.com'
