name: release

on:
  push:
    tags:
      - "*"

jobs:
  create:
    name: Create Release
    runs-on: ssvm
    container:
      image: secondstate/ssvm:ubuntu-build-gcc
    outputs:
      version: ${{ steps.prep.outputs.version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: prep
        run: |
          echo ::set-output name=version::$(git describe --tag)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: SSVM ${{ steps.prep.outputs.version }}
          body_path: .CurrentChangelog.md
          draft: false
          prerelease: false
  build_amd64:
    name: Build SSVM on amd64 platform
    needs: create
    runs-on: ssvm
    container:
      image: secondstate/ssvm:ubuntu-build-gcc
    steps:
      - name: Build package
        run: |
          apt update
          apt install -y rpm ninja-build
          rm -rf build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOL_SSVM_STATIC=ON -DBUILD_PACKAGE="TGZ;DEB;RPM" .
          cmake --build build
          cmake --build build --target package
  upload_amd64_package:
    name: Upload SSVM amd64 package
    needs: [create, build_amd64]
    runs-on: ssvm
    container:
      image: secondstate/ssvm:ubuntu-build-gcc
    steps:
      - name: Upload ssvm amd64 deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/ssvm_${{ needs.create.outputs.version }}_amd64.deb
          asset_name: SSVM-${{ needs.create.outputs.version }}.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: Upload ssvm-static amd64 deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/ssvm-static_${{ needs.create.outputs.version }}_amd64.deb
          asset_name: SSVM-static-${{ needs.create.outputs.version }}.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: Upload ssvm rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/SSVM-${{ needs.create.outputs.version }}-Linux.rpm
          asset_name: SSVM-${{ needs.create.outputs.version }}.rpm
          asset_content_type: application/x-rpm
      - name: Upload ssvm-static rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/SSVM-${{ needs.create.outputs.version }}-Linux-static.rpm
          asset_name: SSVM-static-${{ needs.create.outputs.version }}.rpm
          asset_content_type: application/x-rpm
  build_manylinux1_x86_64:
    name: Build SSVM on manylinux1_x86_64 platform
    needs: [create, upload_amd64_package]
    runs-on: ssvm
    container:
      image: secondstate/ssvm:manylinux1_x86_64
    steps:
      - name: Build manylinux1_x86_64 package
        run: |
          curl -s -L -O --remote-name-all https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2
          bzip2 -dc boost_1_75_0.tar.bz2 | tar -xf -
          yum check-update
          yum install -y rpm-build
          export PATH="/toolchain/bin:$PATH"
          export CC=gcc
          export CXX=g++
          rm -rf build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_PACKAGE="TGZ;TBZ2;TXZ;TZST;RPM" -DBOOST_INCLUDEDIR=./boost_1_75_0/ .
          cmake --build build
          cmake --build build --target package
  upload_manylinux1_x86_64_package:
    name: Upload SSVM manylinux1 x86_64 package
    needs: [create, build_manylinux1_x86_64]
    runs-on: ssvm
    container:
      image: secondstate/ssvm:ubuntu-build-gcc
    steps:
      - name: Upload manylinux1_x86_64 rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.rpm
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux1_x86_64.rpm
          asset_content_type: application/x-rpm
      - name: Upload manylinux1_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.gz
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux1_x86_64 tar.bz2 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.bz2
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.bz2
          asset_content_type: application/x-bzip2
      - name: Upload manylinux1_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.xz
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload manylinux1_x86_64 tar.zst package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.zst
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.zst
          asset_content_type: application/zstd
  build_manylinux2010_x86_64:
    name: Build SSVM on manylinux2010_x86_64 platform
    needs: [create, upload_manylinux1_x86_64_package]
    runs-on: ssvm
    container:
      image: secondstate/ssvm:manylinux2010_x86_64
    steps:
      - name: Build manylinux2010_x86_64 package
        run: |
          curl -s -L -O --remote-name-all https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2
          bzip2 -dc boost_1_75_0.tar.bz2 | tar -xf -
          yum check-update
          yum install -y rpm-build
          export PATH="/toolchain/bin:$PATH"
          export CC=gcc
          export CXX=g++
          rm -rf build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_PACKAGE="TGZ;TBZ2;TXZ;TZST;RPM" -DBOOST_INCLUDEDIR=./boost_1_75_0/ .
          cmake --build build
          cmake --build build --target package
  upload_manylinux2010_x86_64_package:
    name: Upload SSVM manylinux2010 x86_64 package
    needs: [create, build_manylinux2010_x86_64]
    runs-on: ssvm
    container:
      image: secondstate/ssvm:ubuntu-build-gcc
    steps:
      - name: Upload manylinux2010_x86_64 rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.rpm
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2010_x86_64.rpm
          asset_content_type: application/x-rpm
      - name: Upload manylinux2010_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.gz
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2010_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux2010_x86_64 tar.bz2 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.bz2
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2010_x86_64.tar.bz2
          asset_content_type: application/x-bzip2
      - name: Upload manylinux2010_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.xz
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2010_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload manylinux2010_x86_64 tar.zst package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.zst
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2010_x86_64.tar.zst
          asset_content_type: application/zstd
  build_manylinux2014_x86_64:
    name: Build SSVM on manylinux2014_x86_64 platform
    needs: [create, upload_manylinux2010_x86_64_package]
    runs-on: ssvm
    container:
      image: secondstate/ssvm:manylinux2014_x86_64
    steps:
      - name: Build manylinux2014_x86_64 package
        run: |
          curl -s -L -O --remote-name-all https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2
          bzip2 -dc boost_1_75_0.tar.bz2 | tar -xf -
          yum check-update
          yum install -y rpm-build
          export PATH="/toolchain/bin:$PATH"
          export CC=gcc
          export CXX=g++
          rm -rf build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_PACKAGE="TGZ;TBZ2;TXZ;TZST;RPM" -DBOOST_INCLUDEDIR=./boost_1_75_0/ .
          cmake --build build
          cmake --build build --target package
  upload_manylinux2014_x86_64_package:
    name: Upload SSVM manylinux2014 x86_64 package
    needs: [create, build_manylinux2014_x86_64]
    runs-on: ssvm
    container:
      image: secondstate/ssvm:ubuntu-build-gcc
    steps:
      - name: Upload manylinux2014_x86_64 rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.rpm
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2014_x86_64.rpm
          asset_content_type: application/x-rpm
      - name: Upload manylinux2014_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.gz
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux2014_x86_64 tar.bz2 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.bz2
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.bz2
          asset_content_type: application/x-bzip2
      - name: Upload manylinux2014_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.xz
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload manylinux2014_x86_64 tar.zst package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: SSVM-${{ needs.create.outputs.version }}-Linux.tar.zst
          asset_name: SSVM-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.zst
          asset_content_type: application/zstd
