name: release

on:
  push:
    tags:
      - "*"

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc
    outputs:
      version: ${{ steps.prep.outputs.version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: prep
        run: |
          echo ::set-output name=version::$(git describe --tag)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: WasmEdge ${{ steps.prep.outputs.version }}
          body_path: .CurrentChangelog.md
          draft: false
          prerelease: false
  build_and_upload_amd64_package:
    name: Build WasmEdge on amd64 platform and upload WasmEdge amd64 package
    needs: create
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build package
        run: |
          apt update
          apt install -y rpm ninja-build
          rm -rf build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOL_WASMEDGE_STATIC=ON -DBUILD_PACKAGE="TGZ;DEB;RPM" .
          cmake --build build
          cmake --build build --target package
      - name: Upload WasmEdge amd64 deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/wasmedge_${{ needs.create.outputs.version }}_amd64.deb
          asset_name: WasmEdge-${{ needs.create.outputs.version }}.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: Upload wasmedge-static amd64 deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/wasmedge-static_${{ needs.create.outputs.version }}_amd64.deb
          asset_name: WasmEdge-static-${{ needs.create.outputs.version }}.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: Upload wasmedge rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.rpm
          asset_name: WasmEdge-${{ needs.create.outputs.version }}.rpm
          asset_content_type: application/x-rpm
      - name: Upload wasmedge-static rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux-static.rpm
          asset_name: WasmEdge-static-${{ needs.create.outputs.version }}.rpm
          asset_content_type: application/x-rpm
  build_and_upload_manylinux1_x86_64_package:
    name: Build WasmEdge on manylinux1_x86_64 platform and upload WasmEdge manylinux1 x86_64 package
    needs: create
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:manylinux1_x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build manylinux1_x86_64 package
        run: |
          curl -s -L -O --remote-name-all https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.bz2
          bzip2 -dc boost_1_75_0.tar.bz2 | tar -xf -
          export PATH="/toolchain/bin:$PATH"
          export CC=gcc
          export CXX=g++
          rm -rf build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOL_WASMEDGE_STATIC=OFF -DBUILD_PACKAGE="TGZ;TBZ2;TXZ;TZST;RPM" -DBOOST_INCLUDEDIR=./boost_1_75_0/ .
          cmake --build build
          cmake --build build --target package
      - name: Upload manylinux1_x86_64 rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.rpm
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux1_x86_64.rpm
          asset_content_type: application/x-rpm
      - name: Upload manylinux1_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.gz
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux1_x86_64 tar.bz2 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.bz2
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.bz2
          asset_content_type: application/x-bzip2
      - name: Upload manylinux1_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.xz
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload manylinux1_x86_64 tar.zst package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.zst
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.zst
          asset_content_type: application/zstd
  build_and_upload_manylinux2010_x86_64_package:
    name: Build WasmEdge on manylinux2010_x86_64 platform and upload WasmEdge manylinux2010 x86_64 package
    needs: create
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:manylinux2010_x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build manylinux2010_x86_64 package
        run: |
          curl -s -L -O --remote-name-all https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.bz2
          bzip2 -dc boost_1_75_0.tar.bz2 | tar -xf -
          export PATH="/toolchain/bin:$PATH"
          export CC=gcc
          export CXX=g++
          rm -rf build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOL_WASMEDGE_STATIC=OFF -DBUILD_PACKAGE="TGZ;TBZ2;TXZ;TZST;RPM" -DBOOST_INCLUDEDIR=./boost_1_75_0/ .
          cmake --build build
          cmake --build build --target package
      - name: Upload manylinux2010_x86_64 rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.rpm
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2010_x86_64.rpm
          asset_content_type: application/x-rpm
      - name: Upload manylinux2010_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.gz
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2010_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux2010_x86_64 tar.bz2 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.bz2
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2010_x86_64.tar.bz2
          asset_content_type: application/x-bzip2
      - name: Upload manylinux2010_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.xz
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2010_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload manylinux2010_x86_64 tar.zst package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.zst
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2010_x86_64.tar.zst
          asset_content_type: application/zstd
  build_and_upload_manylinux2014_x86_64_package:
    name: Build WasmEdge on manylinux2014_x86_64 platform and upload WasmEdge manylinux2014 x86_64 package
    needs: create
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:manylinux2014_x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build manylinux2014_x86_64 package
        run: |
          curl -s -L -O --remote-name-all https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.bz2
          bzip2 -dc boost_1_75_0.tar.bz2 | tar -xf -
          export PATH="/toolchain/bin:$PATH"
          export CC=gcc
          export CXX=g++
          rm -rf build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOL_WASMEDGE_STATIC=OFF -DBUILD_PACKAGE="TGZ;TBZ2;TXZ;TZST;RPM" -DBOOST_INCLUDEDIR=./boost_1_75_0/ .
          cmake --build build
          cmake --build build --target package
      - name: Upload manylinux2014_x86_64 rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.rpm
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2014_x86_64.rpm
          asset_content_type: application/x-rpm
      - name: Upload manylinux2014_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.gz
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux2014_x86_64 tar.bz2 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.bz2
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.bz2
          asset_content_type: application/x-bzip2
      - name: Upload manylinux2014_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.xz
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload manylinux2014_x86_64 tar.zst package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create.outputs.version }}-Linux.tar.zst
          asset_name: WasmEdge-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.zst
          asset_content_type: application/zstd
