name: release

concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "*"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc
    outputs:
      version: ${{ steps.prep.outputs.version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: prep
        run: |
          echo ::set-output name=version::$(git describe --tag)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: WasmEdge ${{ steps.prep.outputs.version }}
          body_path: .CurrentChangelog.md
          draft: true
          prerelease: false
  build_on_ubuntu:
    strategy:
      matrix:
        include:
          - name: ubuntu 20.04 x86_64
            docker_tag: ubuntu2004_x86_64
            os: ubuntu20.04
    name: Build and upload WasmEdge on ${{ matrix.name }} platform
    needs: create_release
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:${{ matrix.docker_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build package
        run: |
          apt update
          apt install -y rpm ninja-build
          rm -rf build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_PACKAGE="TGZ;DEB;RPM" .
          cmake --build build
          cmake --build build --target package
      - name: Upload deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/wasmedge_${{ needs.create_release.outputs.version }}_amd64.deb
          asset_name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.os }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: Upload rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.rpm
          asset_name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.os }}_amd64.rpm
          asset_content_type: application/x-rpm
      - name: Upload tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.tar.gz
          asset_name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.os }}_amd64.tar.gz
          asset_content_type: application/x-gzip

  build_on_manylinux_legacy:
    strategy:
      matrix:
        include:
          - name: manylinux1_x86_64
            docker_tag: manylinux1_x86_64
          - name: manylinux2010_x86_64
            docker_tag: manylinux2010_x86_64
    name: Build on ${{ matrix.name }} platform
    needs: create_release
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:${{ matrix.docker_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build ${{ matrix.name }} package
        run: |
          bash utils/docker/build-manylinux.sh
      - name: Upload rpm package to artifact
        uses: actions/upload-artifact@v1
        with:
          name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.rpm
          path: build/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.rpm
      - name: Upload ${{ matrix.name }} tar.gz package to artifact
        uses: actions/upload-artifact@v1
        with:
          name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.gz
          path: build/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.tar.gz
      - name: Upload ${{ matrix.name }} tar.xz package to artifact
        uses: actions/upload-artifact@v1
        with:
          name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.xz
          path: build/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.tar.xz
  upload_manylinux_legacy:
    strategy:
      matrix:
        include:
          - name: manylinux1_x86_64
          - name: manylinux2010_x86_64
    name: Upload WasmEdge ${{ matrix.name }} package
    needs: [create_release, build_on_manylinux_legacy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download ${{ matrix.name }} rpm artifact
        uses: actions/download-artifact@v1
        with:
          name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.rpm
      - name: Verify the arifact
        run: |
          ls -alh .
          ls -alh WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.rpm
      - name: Upload ${{ matrix.name }} rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.rpm/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.rpm
          asset_name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.rpm
          asset_content_type: application/x-rpm
      - name: Download ${{ matrix.name }} tar.gz artifact
        uses: actions/download-artifact@v1
        with:
          name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.gz
      - name: Upload ${{ matrix.name }} tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.gz/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.tar.gz
          asset_name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.gz
          asset_content_type: application/x-gzip
      - name: Download ${{ matrix.name }} tar.xz artifact
        uses: actions/download-artifact@v1
        with:
          name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.xz
      - name: Upload ${{ matrix.name }} tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.xz/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.tar.xz
          asset_name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.xz
          asset_content_type: application/x-xz

  build_and_upload_manylinux2014:
    strategy:
      matrix:
        include:
          - name: manylinux2014_x86_64
            docker_tag: manylinux2014_x86_64
            host_runner: ubuntu-latest
          - name: manylinux2014_aarch64
            docker_tag: manylinux2014_aarch64
            host_runner: ARM64
    name: Build and upload WasmEdge on ${{ matrix.name }} platform
    needs: create_release
    runs-on: ${{ matrix.host_runner }}
    container:
      image: wasmedge/wasmedge:${{ matrix.docker_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build ${{ matrix.name }} package
        run: |
          bash utils/docker/build-manylinux.sh
      - name: Upload ${{ matrix.name }} rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.rpm
          asset_name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.rpm
          asset_content_type: application/x-rpm
      - name: Upload ${{ matrix.name }} tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.tar.gz
          asset_name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload ${{ matrix.name }} tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/WasmEdge-${{ needs.create_release.outputs.version }}-Linux.tar.xz
          asset_name: WasmEdge-${{ needs.create_release.outputs.version }}-${{ matrix.name }}.tar.xz
          asset_content_type: application/x-xz
