name: release

on:
  push:
    tags:
      - "*"

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: secondstate/ssvm:ubuntu-build-gcc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: prep
        run: |
          echo ::set-output name=version::$(git describe --tag)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: SSVM ${{ steps.prep.outputs.version }}
          draft: false
          prerelease: false
      - name: Build package
        run: |
          apt update
          apt install -y rpm ninja-build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release .
          cmake --build build --target package
      - name: Upload deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/SSVM-${{ steps.prep.outputs.version }}-Linux.deb
          asset_name: SSVM-${{ steps.prep.outputs.version }}.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: Upload rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/SSVM-${{ steps.prep.outputs.version }}-Linux.rpm
          asset_name: SSVM-${{ steps.prep.outputs.version }}.rpm
          asset_content_type: application/x-rpm
      - name: Build manylinux1_x86_64 package
        uses: addnab/docker-run-action@v1
        with:
          image: secondstate/ssvm:manylinux1_x86_64
          run: /toolchain/build-manylinux.sh
          options: -v .:/ssvm --rm
      - name: Upload manylinux1_x86_64 rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.rpm
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux1_x86_64.rpm
          asset_content_type: application/x-rpm
      - name: Upload manylinux1_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.gz
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux1_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux1_x86_64 tar.bz2 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.bz2
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux1_x86_64.tar.bz2
          asset_content_type: application/x-bzip2
      - name: Upload manylinux1_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.xz
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux1_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload manylinux1_x86_64 tar.zst package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.zst
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux1_x86_64.tar.zst
          asset_content_type: application/zstd
      - name: Build manylinux2010_x86_64 package
        uses: addnab/docker-run-action@v1
        with:
          image: secondstate/ssvm:manylinux2010_x86_64
          run: /toolchain/build-manylinux.sh
          options: -v .:/ssvm --rm
      - name: Upload manylinux2010_x86_64 rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.rpm
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2010_x86_64.rpm
          asset_content_type: application/x-rpm
      - name: Upload manylinux2010_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.gz
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2010_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux2010_x86_64 tar.bz2 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.bz2
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2010_x86_64.tar.bz2
          asset_content_type: application/x-bzip2
      - name: Upload manylinux2010_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.xz
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2010_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload manylinux2010_x86_64 tar.zst package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.zst
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2010_x86_64.tar.zst
          asset_content_type: application/zstd
      - name: Build manylinux2014_x86_64 package
        uses: addnab/docker-run-action@v1
        with:
          image: secondstate/ssvm:manylinux2014_x86_64
          run: /toolchain/build-manylinux.sh
          options: -v .:/ssvm --rm
      - name: Upload manylinux2014_x86_64 rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.rpm
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2014_x86_64.rpm
          asset_content_type: application/x-rpm
      - name: Upload manylinux2014_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.gz
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2014_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux2014_x86_64 tar.bz2 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.bz2
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2014_x86_64.tar.bz2
          asset_content_type: application/x-bzip2
      - name: Upload manylinux2014_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.xz
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2014_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload manylinux2014_x86_64 tar.zst package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SSVM.tar.zst
          asset_name: SSVM-${{ steps.prep.outputs.version }}-manylinux2014_x86_64.tar.zst
          asset_content_type: application/zstd
