name: Build extensions on manylinux

on:
  workflow_call:
    inputs:
      arch:
        type: string
        required: true
      runner:
        type: string
        required: true
      docker_tag:
        type: string
        required: true
      asset_tag:
        type: string
        required: true
      plugins:
        type: string
        required: true
      version:
        type: string
        required: true
      release:
        type: boolean
        default: false

env:
  build_tests: ${{ inputs.release && 'Off' || 'On' }}
  build_type: Release

jobs:
  prepare:
    name: Prepare variables
    runs-on: ${{ inputs.runner }}
    outputs:
      cache_key_ws: ${{ steps.prep.outputs.cache_key_ws }}
      cache_path_ws: ${{ steps.prep.outputs.cache_path_ws }}
      cache_key_h: ${{ steps.prep.outputs.cache_key_h }}
      cache_path_h: ${{ steps.prep.outputs.cache_path_h }}
    steps:
      - id: prep
        run: |
          echo "cache_key_ws=${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ inputs.docker_tag }}-1-${{ github.run_id }}" >> $GITHUB_OUTPUT
          echo "cache_path_ws=${{ github.workspace }}" >> $GITHUB_OUTPUT
          echo "cache_key_h=${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ inputs.docker_tag }}-2-${{ github.run_id }}" >> $GITHUB_OUTPUT
          echo "cache_path_h=$HOME" >> $GITHUB_OUTPUT

  prepare_cache:
    needs: [prepare]
    name: Prepare files (${{ inputs.docker_tag }})
    runs-on: ${{ inputs.runner }}
    container:
      image: wasmedge/wasmedge:${{ inputs.docker_tag }}
      # Required for mounting debugfs
      # Tests of wasm_bpf also require privileges
      options: --privileged
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Install dependencies
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
          source "$HOME/.cargo/env"
      - name: Build ${{ matrix.plugin }}
        shell: bash
        run: |
          if [[ ${build_tests} != "On" ]]; then
            target=${bin_name%.*}
            target=${target#lib}
          fi

          mkdir -p build
          cmake -Bbuild -GNinja -DWASMEDGE_BUILD_TESTS=${build_tests} -DCMAKE_BUILD_TYPE=${build_type} -DWASMEDGE_USE_LLVM=OFF -DWASMEDGE_BUILD_TOOLS=OFF -DWASMEDGE_PLUGIN_WASI_LOGGING=ON
          cmake --build build --target wasmedgePluginWasiLogging
      - uses: actions/cache/save@v3
        with:
          key: ${{ needs.prepare.outputs.cache_key_ws }}
          path: ${{ needs.prepare.outputs.cache_path_ws }}
      - uses: actions/cache/save@v3
        with:
          key: ${{ needs.prepare.outputs.cache_key_h }}
          path: ${{ needs.prepare.outputs.cache_path_h }}

  build_on_manylinux:
    needs: [prepare, prepare_cache]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.plugins) }}
    name: ${{ matrix.plugin }} (${{ inputs.docker_tag }})
    runs-on: ${{ inputs.runner }}
    container:
      image: wasmedge/wasmedge:${{ inputs.docker_tag }}
      # Required for mounting debugfs
      # Tests of wasm_bpf also require privileges
      options: --privileged
    env:
      bin_name: ${{ matrix.bin }}
      target: ${{ inputs.release && matrix.bin || matrix.testBin }}
      test_dir: build/test/plugins/${{ matrix.dir }}
      output_dir: build/plugins/${{ matrix.dir }}
    steps:
      - id: prep
        run: |
          echo "artifact=WasmEdge-plugin-${{ matrix.plugin }}-${{ inputs.version }}-${{ inputs.asset_tag }}.tar.gz" >> $GITHUB_OUTPUT
          echo "filename=plugin_${{ matrix.plugin }}.tar.gz" >> $GITHUB_OUTPUT
      - uses: actions/cache/restore@v3
        with:
          key: ${{ needs.prepare.outputs.cache_key_ws }}
          path: ${{ needs.prepare.outputs.cache_path_ws }}
      - uses: actions/cache/restore@v3
        with:
          key: ${{ needs.prepare.outputs.cache_key_h }}
          path: ${{ needs.prepare.outputs.cache_path_h }}
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Install dependencies
        shell: bash
        run: |
          # Running tests of wasm_bpf requires proper ebpf running environment
          mount -t debugfs none /sys/kernel/debug
      - name: Build ${{ matrix.plugin }}
        shell: bash
        run: |
          if [[ ${build_tests} != "On" ]]; then
            target=${bin_name%.*}
            target=${target#lib}
          fi

          cmake -Bbuild -GNinja ${{ matrix.options }}
          cmake --build build --target ${target}

          cp -f ${output_dir}/${bin_name} ${bin_name}
          tar -zcvf ${{ steps.prep.outputs.filename }} ${bin_name}
      - name: Test ${{ matrix.plugin }}
        if: ${{ !inputs.release }}
        run: |
          cd ${test_dir}
          ./${target}
          cd -
      - name: Upload artifact ${{ matrix.plugin }}
        if: ${{ !inputs.release }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prep.outputs.artifact }}
          path: ${{ steps.prep.outputs.filename }}
      - name: Upload WasmEdge ${{ matrix.plugin }} plugin tar.gz package
        if: ${{ inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv ${{ steps.prep.outputs.filename }} ${{ steps.prep.outputs.artifact }}
          gh release upload ${{ inputs.version }} ${{ steps.prep.outputs.artifact }} --clobber
