name: Clang-Format

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04 # https://github.com/actions/runner-images/issues/10636
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Install clang-format-18
        run: |
          sudo apt update
          sudo apt install clang-format-18
      - name: Run clang-format
        run: |
          bash ./.github/scripts/clang-format.sh `which clang-format-18`
