name: Rust Crate Release

concurrency:
  group: rust-crate-release-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "rust/[0-9]+.[0-9]+.[0-9]+*"

jobs:
  crate_release:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build WasmEdge using clang
      run: |
        cmake -Bbuild -GNinja -DWASMEDGE_BUILD_SHARED_LIB=ON .
        cmake --build build

    - name: Publish wasmedge-sys crate
      uses: katyo/publish-crates@v1
      with:
          path: './bindings/rust/wasmedge-sys'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
