name: rust

concurrency:
  group: rust-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rust:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Rustfmt
      run: cargo fmt --all -- --check

    - name: Build WasmEdge using clang with Debug mode
      run: |
        if ! command ninja; then
          apt update
          apt install -y ninja-build
        fi
        cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIB=ON .
        cmake --build build

    - name: Clippy
      run: cargo clippy --profile test -- -D warnings -D clippy::dbg_macro

    - name: Test
      run: cargo test --locked
