name: binding-rust-static-lib

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - "rust/*"
    paths:
      - ".github/workflows/rust-static-lib.yml"
      - "bindings/rust/**"
      - "include/api/wasmedge/**"
      - "lib/api/**"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/rust-static-lib.yml"
      - "bindings/rust/**"
      - "include/api/wasmedge/**"
      - "lib/api/**"

jobs:
  build_ubuntu:
    name: Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rust: [1.69, 1.68]
    container:
      image: wasmedge/wasmedge:latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build WasmEdge with Release mode
        run: |
          apt update
          apt install -y software-properties-common libboost-all-dev llvm-15-dev liblld-15-dev ninja-build
          cmake cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_LINK_LLVM_STATIC=ON -DWASMEDGE_BUILD_SHARED_LIB=OFF -DWASMEDGE_BUILD_STATIC_LIB=ON -DWASMEDGE_LINK_TOOLS_STATIC=ON -DWASMEDGE_BUILD_PLUGINS=OFF .
          cmake --build build

      - name: Install Rust-nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Rustfmt
        working-directory: bindings/rust/
        run: cargo +nightly fmt --all -- --check

      - name: Clippy
        working-directory: bindings/rust/
        run: |
          export WASMEDGE_DIR="$(pwd)/../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../build"
          cargo +nightly clippy -V
          cargo +nightly clippy --lib --examples --features static -- -D warnings

      - name: Install Rust-stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Test Rust Bindings
        working-directory: bindings/rust/
        run: |
          export WASMEDGE_DIR="$(pwd)/../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../build"
          cargo +nightly -Z sparse-registry update
          cargo test --workspace --features static --locked -- --test-threads=1
          cargo test --examples --features static --locked -- --test-threads=1
