name: wasmedge-sys-release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  crate_release:
    name: Create Release
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common libboost-all-dev ninja-build
          sudo apt-get install -y llvm-14-dev liblld-14-dev clang-14
          sudo apt-get install -y gcc g++
          sudo apt-get install -y libssl-dev pkg-config gh

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set git credentials
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Prepare release
        run: |
          cargo install cargo-smart-release

      - name: Build WasmEdge with Release mode
        run: |
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_TESTS=ON .
          cmake --build build

      - name: Dry run cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        shell: bash
        working-directory: bindings/rust/
        run: |
          export WASMEDGE_DIR="$(pwd)/../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../build"
          export WASMEDGE_PLUGIN_PATH="$(pwd)/../../build/plugins/wasmedge_process"
          cargo smart-release --update-crates-index --dry-run-cargo-publish --no-dependencies --no-changelog --no-tag wasmedge-sys

      - name: Publish
        if: github.ref == 'refs/heads/master'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        working-directory: bindings/rust/
        run: |
          export WASMEDGE_DIR="$(pwd)/../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../build"
          export WASMEDGE_PLUGIN_PATH="$(pwd)/../../build/plugins/wasmedge_process"
          cargo smart-release --update-crates-index --execute --no-dependencies --no-changelog --no-tag wasmedge-sys

      - name: Build API document
        working-directory: bindings/rust/wasmedge-sys
        run: |
          export WASMEDGE_DIR="$(pwd)/../../../"
          export WASMEDGE_BUILD_DIR="$(pwd)/../../../build"
          export WASMEDGE_PLUGIN_PATH="$(pwd)/../../../build/plugins/wasmedge_process"
          export LD_LIBRARY_PATH="$(pwd)/../../../build/lib/api"
          cargo doc --all --no-deps --target-dir=./target

      - name: Deploy API document
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: bindings/rust/wasmedge-sys/target/doc
          force_orphan: true
