name: wasmedge-macro-release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  crate_release:
    name: Create Release
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common libboost-all-dev
          sudo apt-get install -y llvm-14-dev liblld-14-dev clang-14
          sudo apt-get install -y gcc g++
          sudo apt-get install -y libssl-dev

      - name: Install Rust v1.65
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.65
          components: rustfmt, clippy

      - name: Dry run cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        shell: bash
        working-directory: bindings/rust/
        run: |
          cargo publish --dry-run -p wasmedge-macro

      - name: Publish
        if: github.ref == 'refs/heads/master'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        working-directory: bindings/rust/
        run: |
          cargo publish -p wasmedge-macro

      - name: Build API document
        working-directory: bindings/rust/wasmedge-macro
        run: |
          cargo doc -p wasmedge-macro --workspace --no-deps --features aot,async,wasi_crypto,wasi_nn --target-dir=./target

      - name: Deploy API document
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: bindings/rust/wasmedge-macro/target/doc
          force_orphan: true
