name: wasmedge-macro-release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  release_wasmedge_macro:
    name: Create Release
    runs-on: ubuntu-22.04
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust v1.68
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68
    
      - name: Dry run cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRIES_MACRO_TOKEN }}
        shell: bash
        working-directory: bindings/rust/
        run: |
          cargo publish --dry-run -p wasmedge-macro

      - name: Publish
        if: github.ref == 'refs/heads/master'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRIES_MACRO_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        working-directory: bindings/rust/
        run: |
          cargo publish -p wasmedge-macro

      - name: Build API document
        working-directory: bindings/rust/
        run: |
          cargo doc -p wasmedge-macro --no-deps --target-dir=./target

      - name: Deploy API document
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: bindings/rust/target/doc
          force_orphan: true
