name: rust-standalone-test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    branches:
      - master
      - "rust/*"
      - "ci/update-rust-standalone"

jobs:
  build_ubuntu_2204:
    name: Ubuntu-22.04
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build WasmEdge with Release mode
        run: |
          apt update
          apt install -y software-properties-common libboost-all-dev llvm-12-dev liblld-12-dev ninja-build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_PROCESS=On .
          cmake --build build
  
      - name: Install Rust v1.68
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68

      - name: Run in the standalone mode
        working-directory: bindings/rust/
        run: |
          export LLVM_DIR="/usr/local/opt/llvm/lib/cmake"
          export CC=clang
          export CXX=clang++
          export LD_LIBRARY_PATH=$HOME/.wasmedge/lib
          export WASMEDGE_DIR="$(pwd)/../../"
          cargo test -p wasmedge-sdk --all --examples --features standalone

  build_ubuntu_2004:
    name: Ubuntu-20.04
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common libboost-all-dev ninja-build
          sudo apt-get install -y llvm-12-dev liblld-12-dev clang-12
          sudo apt-get install -y gcc g++
          sudo apt-get install -y libssl-dev pkg-config gh

      - name: Install Rust v1.68
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68

      - name: Run in the standalone mode
        working-directory: bindings/rust/
        run: |
          export LLVM_DIR="/usr/local/opt/llvm@12/lib/cmake"
          export CC=clang
          export CXX=clang++
          export LD_LIBRARY_PATH=$HOME/.wasmedge/lib
          export WASMEDGE_DIR="$(pwd)/../../"
          cargo +nightly -Z sparse-registry update
          cargo test -p wasmedge-sdk --all --examples --features standalone

  build_macos:
    name: MacOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust v1.68
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68

      - name: Install build tools
        run: brew install llvm ninja boost cmake

      - name: Install libwasmedge
        working-directory: bindings/rust/
        run: |
          export LLVM_DIR="/usr/local/opt/llvm/lib/cmake"
          export CC=clang
          export CXX=clang++
          export DYLD_LIBRARY_PATH="/Users/runner/.wasmedge/lib"
          export WASMEDGE_DIR="$(pwd)/../../"
          cargo +nightly -Z sparse-registry update
          cargo test -p wasmedge-sdk --all --examples --features standalone
