name: rust

concurrency:
  group: rust-standalone-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  standalone:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Install Nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy

    - name: Test
      run: |
        cd bindings/rust/
        export WASMEDGE_DIR="$(pwd)/../../"
        cargo test --lib --examples
        cargo test --doc
