name: wasmedge-sys-docs

concurrency:
  group: wasmedge-sys-docs-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "rust/[0-9]+.[0-9]+.[0-9]+*"

jobs:
  rustdoc:
    name: rustdoc
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Build Documentation
        run: |
          cd bindings/rust/wasmedge-sys
          cargo doc --all --no-deps --target-dir=./target
          echo "<meta http-equiv=\"refresh\" content=\"0; url=wasmedge_sys\">" > target/doc/index.html

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: bindings/rust/wasmedge-sys/target/doc
          force_orphan: true
