name: Submit WasmEdge MSI package to the Windows Package Manager Community Repository

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Submit WasmEdge MSI package with Winget-Releaser
        uses: vedantmgoyal9/winget-releaser@b3a5dae0047c6180023acba3f548c55fdf6b7193 # main
        with:
          identifier: WasmEdge.WasmEdge
          installers-regex: 'windows\.msi$'
          token: ${{ secrets.GITHUB_TOKEN }}
