name: Submit WasmEdge MSI package to the Windows Package Manager Community Repository

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Submit WasmEdge MSI package with Winget-Releaser
        uses: vedantmgoyal9/winget-releaser@7bd472be23763def6e16bd06cc8b1cdfab0e2fd5 # main
        with:
          identifier: WasmEdge.WasmEdge
          installers-regex: 'windows\.msi$'
          token: ${{ secrets.GITHUB_TOKEN }}
