name: Submit WasmEdge MSI package to the Windows Package Manager Community Repository

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Submit WasmEdge MSI package with Winget-Releaser
        uses: vedantmgoyal9/winget-releaser@7bd472be23763def6e16bd06cc8b1cdfab0e2fd5 # main
        with:
          identifier: WasmEdge.WasmEdge
          installers-regex: 'windows\.msi$'
          token: ${{ secrets.GITHUB_TOKEN }}
